Feat/apple developer
catppuccin/userstyles pull request #1044
Opened 2024-07-04 03:55 UTC by AyaanAhmed25

## 🎉 Theme for [Apple developer documentation](https://developer.apple.com/documentation) 🎉

Apple's official documentation site.

![preview](https://github.com/catppuccin/userstyles/assets/114197209/adbf52b9-6d96-4811-b676-22892e12a1dc)

## 💬 Additional Comments 💬

Was unsure whether to make the link colors accent-color or blue, went with blue in the end. Feel free to change. 

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/scripts/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - `catppuccin.user.css` - all the CSS for the userstyle, based on the
    template.
  - `preview.webp` - composite image of all four individual flavor screenshots stitched together,
    generated via [Catwalk](https://github.com/catppuccin/toolbox/tree/main/catwalk#readme).

2024-07-04 03:59 UTC, uncenter requested changes

2024-07-04 03:59 UTC, uncenter commented on scripts/userstyles.yml
> +    categories: [development, productivity]
```suggestion
  apple-developer-documentation:
    name: Apple Developer Documentation
    categories: [development, wiki]
```

2024-07-04 03:59 UTC, uncenter commented on scripts/userstyles.yml
> +      usage: "Make sure stylus theme and website theme (all the way at the bottom of the webpage) match"
```suggestion
```

2024-07-04 03:59 UTC, uncenter commented on scripts/userstyles.yml
> +      current-maintainers: [*AyaanAhmed25]
```suggestion
    current-maintainers: [*AyaanAhmed25]
```

2024-07-04 03:59 UTC, uncenter commented on styles/apple-developer/catppuccin.user.css
> +    }
```suggestion
```

2024-07-04 03:59 UTC, uncenter commented on styles/apple-developer/catppuccin.user.css
> +  }
Please update these to correctly detect the website's color scheme from the `data-color-scheme` attribute.

2024-07-04 03:59 UTC, uncenter commented on styles/apple-developer/catppuccin.user.css
> +
```suggestion
```

2024-07-04 04:30 UTC, uncenter commented
Please rename the `styles/apple-developer/` directory to `styles/apple-developer-documentation`.

2024-07-04 05:45 UTC, AyaanAhmed25 commented
@uncenter 
do you want me to rename apple-developer to apple-developer-documentation everywhere?

2024-07-04 10:06 UTC, isabelroses commented
> do you want me to rename apple-developer to apple-developer-documentation everywhere?A

Yes, you should.

2024-07-04 10:08 UTC, isabelroses commented
Also please try to fix the linter errors, most should be easy with `deno task lint:fix`

2024-07-04 12:17 UTC, uncenter commented on styles/apple-developer-documentation/catppuccin.user.css
> +  [data-color-scheme="light"] {
```suggestion
  body[data-color-scheme="light"] {
```

2024-07-04 12:17 UTC, uncenter commented on styles/apple-developer-documentation/catppuccin.user.css
> +  */
```suggestion
```

2024-07-04 14:28 UTC, uncenter commented on styles/apple-developer-documentation/catppuccin.user.css
> +    --color-navigator-item-hover: rgba(0,113,227,.2);
```suggestion
    --color-navigator-item-hover: fade(@accent-color, 30%);
```

2024-07-04 14:58 UTC, AyaanAhmed25 commented
@uncenter Im sorry for all the delays im new to this stuff. Is there anything I need to do now? I see in the reviews section it says 1 change requested, but I dont see anything regarding the change itself
<img width="958" alt="Screenshot 2024-07-04 at 10 57 43 AM" src="https://github.com/catppuccin/userstyles/assets/114197209/938a3ea6-8772-401b-a018-a89128463c7e">

2024-07-04 15:00 UTC, uncenter commented
I'm seeing a lot of unthemed variables. Can you add colors to them?

2024-08-12 19:46 UTC, sgoudham commented
Hey @AyaanAhmed25 :wave: 

Are you still interested in continuing your work here? @uncenter's comment suggests that there are still some variables to be themed?

2025-03-11 20:15 UTC, uncenter commented
Closing as stale.

2025-03-11 20:15 UTC, closed without merging