refactor(canvas-lms): rewrite
catppuccin/userstyles pull request #1084
Opened 2024-07-18 13:06 UTC by pynappo

(reopening because I didn't name my branch properly, apologies)

## 🔧 What does this fix? 🔧

- Borders are themed to less standout colors
- User content (i.e. text with user-added highlights/text color) will keep their original styles when needed
- Course-specific colors are preserved
- Links are themed
- Most buttons are themed and have proper hover color changes
- Accent color is more prominent wherever appropriate/possible
- `color-scheme` variable fixed
- Might fix #368 although I haven't seen the issue with the old nor the new userstyle, seems like the quiz UI is a little different on canvas now
- etc.

<details><summary>Before/After on Catppuccin Mocha with Green accent color</summary>
<p>

(white borders on the screenshot are my browser not the userstyles)

### Dashboard

Before
![current dashboard](https://github.com/user-attachments/assets/f8510fc0-b466-4ff9-af2f-a60e521881af)

After
![rewrite dashboard](https://github.com/user-attachments/assets/908edc4c-004b-4c9b-99c0-b60ebfd89d6d)

### Example Course Homepage

Before
![current course homepage](https://github.com/user-attachments/assets/efad4f65-3e70-4d42-9423-e9a35506619b)

After
![rewrite course homepage](https://github.com/user-attachments/assets/c8f97f0f-d28a-4a0a-bc5e-0f8d4a567070)

### Example Quiz

Before
![current quiz](https://github.com/user-attachments/assets/b1b9366f-bea0-4625-a619-8258ecae1eb1)

After
![rewrite quiz](https://github.com/user-attachments/assets/efcd80eb-1979-4f94-ad8b-03041e0cf422)

### Example Course Modules

Before
![current modules](https://github.com/user-attachments/assets/6242adc4-852a-42c8-8b0f-babf910912b7)

After
![rewrite modules](https://github.com/user-attachments/assets/11ca63cc-229d-442b-a346-dc40feef009b)

</p>
</details>

I've themed the main pages that I've used as a student during my summer courses:

- quizzes
- discussions
- course modules/pages
- grades
- calendar
- inbox
- dashboard
- announcements
- people
- most UI components such as overlays/text editing toolbars/buttons/etc.
- probably some more that I'm forgetting

(A lot of the canvas CSS is autogenerated but with stable suffixes/prefixes/children, hence the high use of attribute selectors and such)

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [x] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.
- [ ] Add webp
- [ ] Clean up the CSS
- [ ] Theme less-used pages (Canvas Studio, instructor-side UI, etc)
- [ ] Test Latte theme
- [ ] See if anything should be added to the userstyles.yml `readme`

2024-07-18 19:29 UTC, uncenter requested changes

2024-07-18 19:29 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.css
> +    @color-scheme: if(@lookup = latte, light, dark);
```suggestion
    color-scheme: if(@lookup = latte, light, dark);
```

2024-07-18 19:29 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.css
> +          filter: brightness(if(( @color-scheme = dark ), 130%, 100%));
```suggestion
          filter: brightness(if((@lookup != latte), 130%, 100%));
```

2024-07-18 19:29 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.css
> +          filter: brightness(if(( @color-scheme = dark ), 130%, 100%));
We also have better solutions for theming PNGs with filters, provided the image is a single color.

2024-11-12 15:04 UTC, uncenter requested changes
Some unthemed areas I'm noticing:

Assignment status (green text):

![CleanShot 2024-11-12 at 09 55 43](https://github.com/user-attachments/assets/3e3ef047-9fba-4df5-b7fa-26b6886ae0bd)
![CleanShot 2024-11-12 at 09 57 54](https://github.com/user-attachments/assets/7c7c81c4-d21a-400c-af05-d4ce7b912665)


Submit/new attempt bar and button at bottom of assignment page:

![CleanShot 2024-11-12 at 09 56 24](https://github.com/user-attachments/assets/f5154585-be4b-4fa6-a16b-07d2fef62aeb)
![CleanShot 2024-11-12 at 09 58 10](https://github.com/user-attachments/assets/14b35789-e302-4d27-ad55-3f65af51d7bd)

The bar is also unthemed (probably the same bar but just for example) on assignments without submission:

![CleanShot 2024-11-12 at 10 00 45](https://github.com/user-attachments/assets/a54cc8a8-8496-4ec7-9fe5-0fbdcc6926c0)

Apply button on grades page should be normal accent, not sure why it is this dark:

![CleanShot 2024-11-12 at 09 57 19](https://github.com/user-attachments/assets/d3d1f44e-820b-405b-9dec-2f3d03323d2d)

Side bar color:

![CleanShot 2024-11-12 at 09 58 29](https://github.com/user-attachments/assets/16ff4f5c-5bb8-48b0-bb83-af1d1116ab99)

Dashboard list view notifications indicator and modal:

![CleanShot 2024-11-12 at 09 59 09](https://github.com/user-attachments/assets/6f54528e-19cb-4154-a9c4-882ad641fd36)

The notification counter/indicator (marked with an arrow) should be themed, as should the bar under the tabs, as should the notification content.

Web URL submission box:

![CleanShot 2024-11-12 at 10 01 41](https://github.com/user-attachments/assets/0795f673-d92d-4e5b-9144-91ba43a61d82)

File upload submission box:

![CleanShot 2024-11-12 at 10 02 02](https://github.com/user-attachments/assets/724e5365-8ba5-448d-9629-881ae6e42bce)

Rubric tables look off because the text has a different background to the table itself:

![CleanShot 2024-11-12 at 10 02 46](https://github.com/user-attachments/assets/ea93990d-4c40-4170-9b45-d0371401cc1b)

2024-11-12 15:23 UTC, uncenter commented
Missing tag thingy is unthemed:

![CleanShot 2024-11-12 at 10 21 37](https://github.com/user-attachments/assets/071a3eb7-67a4-4734-a745-b5aeefcac8fa)

And speaking of the file upload thing I mentioned in the above comment, the modals for the Canvas Files and Webcam Photo and probably Media Recording as well are unthemed:

![CleanShot 2024-11-12 at 10 22 04](https://github.com/user-attachments/assets/f9c80b8a-ec07-4a30-967c-1765f8d64920)

2024-11-12 15:23 UTC, uncenter commented
I was able to use the following CSS to theme all of those little and sometimes big spinners Canvas uses:

```css
[class*="spinner__circleTrack"] {
    stroke: @surface1 !important;
}
[class*="spinner__circleSpin"] {
    stroke: @accent-color !important;
}
```

2024-11-13 00:08 UTC, uncenter commented
I'm going to add a "waiting-on-author" label - no pressure, just signals to maintainers at a glance that a review is not required yet. Please leave a comment once you believe you have implemented the suggested changes and fixed the unthemed areas :)

2024-11-13 01:00 UTC, pynappo commented
For the assignment-page/upload styles, i don't think canvas.instructure.com nor my school's instance has [Enhanced Assignments](https://community.canvaslms.com/t5/Canvas-Basics-Guide/What-is-Assignment-Enhancements/ta-p/416679) enabled so if I could get some html snippets/css styles for those that'd be greatly appreciated.

For sidebar, I left that unstyled because I thought it would help with people who enroll at multiple colleges. Should I just style it according to accent-color?

2024-11-13 01:46 UTC, uncenter commented
> For sidebar, I left that unstyled because I thought it would help with people who enroll at multiple colleges. Should I just style it according to accent-color?

I would say make it mantle?

2024-11-13 03:05 UTC, uncenter commented
Pushed some fixes. Not complete yet, and not in the right place lol. Trying to juggle some files with new documentation I plan to introduce to go along with some of the stuff in that commit. If you want you can organize the new enhanced assignments section stuff I added into the right place and I'll keep working on it wherever you move it to when I get back to it.

2024-11-13 14:12 UTC, uncenter commented
Lots of these buttons all over, I themed some more specifically in the enhanced UI section but we should get better selectors to match them all.

(from a discussion)

<img width="225" alt="image" src="https://github.com/user-attachments/assets/df448614-3d14-4c0f-af90-92ea506a927b">

Here is the HTML from above for your reference:

```html
<span class="discussion-topic-reply-button"><button dir="ltr" data-testid="discussion-topic-reply" cursor="pointer" type="button" tabindex="0" class="css-1iimhyf-view--inlineBlock-baseButton"><span class="css-1mnegct-baseButton__content"><span class="css-11xkk0o-baseButton__children"><span wrap="normal" letter-spacing="normal" class="css-1fvrx9c-text">Reply</span></span></span></button></span>
```

Canvas is using the following CSS to theme it:

```css
.css-1mnegct-baseButton__content {
    box-sizing: border-box;
    width: 100%;
    display: block;
    direction: inherit;
    user-select: none;
    transition: background 0.2s, transform 0.2s;
    transform: none;
    font-family: LatoWeb, "Lato Extended", Lato, "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-weight: 400;
    text-transform: none;
    letter-spacing: normal;
    border-style: solid;
    border-width: 0.0625rem;
    border-radius: 0.25rem;
    line-height: 1.125;
    text-align: center;
    font-size: 1rem;
    padding-left: 0.75rem;
    padding-right: 0.75rem;
    color: rgb(255, 255, 255);
    background: rgb(3, 116, 181);
    border-color: rgb(2, 84, 131);
}

.css-1iimhyf-view--inlineBlock-baseButton:hover > [class$="-baseButton__content"] {
    background: rgb(2, 84, 131);
}
```

You can see `-baseButton__content` is part of the class that is targeted here. Searching this finds that you are already theming some of these types of buttons, though you are using autogenerated classnames in some places - please avoid that if possible so we can catch more of these buttons in our theming.

2024-11-13 14:13 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.css
> +      background-color: @surface0;
```suggestion
      background-color: @surface0;
      border-color: @overlay2;
```

2024-11-13 14:14 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.css
> +      background-color: @surface0;
| Before | After |
| --- | --- |
| ![CleanShot 2024-11-13 at 09 14 00](https://github.com/user-attachments/assets/0fef6fe0-2250-4f8e-a026-79c7ae75575b) | ![CleanShot 2024-11-13 at 09 13 52](https://github.com/user-attachments/assets/53331b03-7eb2-4c69-8070-75a74d6cdaf7) |

2025-01-28 11:01 UTC, pynappo commented
Oops didn't mean to request a review sorry

> You can see `-baseButton__content` is part of the class that is targeted here. Searching this finds that you are already theming some of these types of buttons, though you are using autogenerated classnames in some places - please avoid that if possible so we can catch more of these buttons in our theming.

Hard to avoid, I think relying on at least some auto-generated (React?) class names and documenting where they may appear is the easier path for maintenance. canvas has way too many places that use auto-generated css. The main one targeted, `css-1rpus1y-baseButton__content` covers a majority of the neutral-colored buttons, i'll see if there's only a few more to target

2025-01-28 12:25 UTC, uncenter commented
I'm going to do a squash merge of all your commits on this branch and then rebase it with main now. Is that okay?

2025-01-29 02:18 UTC, pynappo commented
> I'm going to do a squash merge of all your commits on this branch and then rebase it with main now. Is that okay?

yep, go ahead!

2025-01-29 22:27 UTC, uncenter commented
Can you invite me as a collaborator to your userstyles fork? Having more annoying issues with Git refusing my pushes because I'm "uploading LFS objects" (I'm not).

2025-01-29 22:32 UTC, uncenter commented
(None of this is your fault, just Git and Git LFS and GitHub not cooperating.)

2025-01-30 03:07 UTC, uncenter commented
All the changes should be there, except the preview image (it needs to be retaken anyways). There are no more conflicts, but the linter is complaining about a few things - `deno task lint:fix canvas-lms` should autofix most/all of them for you.

2025-02-01 15:42 UTC, uncenter commented
When taking the preview can you try to make Canvas take up the whole screen? Looks like only the first half of the preview image actually has Canvas on it. Also if you haven't already see https://github.com/catppuccin/userstyles/blob/main/docs/tips-and-tricks/convert-images-to-webp.md for our recommendation on converting images to WebP (seeing some color quality loss in the current preview).

2025-02-01 23:34 UTC, pynappo commented
i think the preview should be good now, lmk if you want me to remove the slightly low res png one of my classes has and i'll just retake it.

also, does catwalk handle the conversion from png to webp as well? or is converting the png screenshots to webp via command still preferred?

2025-02-01 23:38 UTC, uncenter commented
I personally convert before Catwalk-ing, I haven't exactly tested it though. It's also easier because I have a shell script `png_to_webp` to recursively convert to WebP, and Catwalk defaults to looking for `<flavor>.webp` files in the CWD - so all I need to do is `png_to_webp && catwalk`.

2025-02-13 13:35 UTC, uncenter commented
Woah this is looking really good. Nice work. I think I'm good to merge this, thought I'd mention this minor issue in the compose message modal of the inbox:

![CleanShot 2025-02-13 at 08 33 47](https://github.com/user-attachments/assets/16245481-8029-47db-a94e-592135f679db)

I don't want to take up too much more of your time and energy, so if you don't have the chance to get to that soon I'll just merge today :)

2025-02-13 13:44 UTC, uncenter requested changes

2025-02-13 13:44 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +@var checkbox styleNavMenu "Style navigation menu" 1
I'm honestly not sure we need this. I don't see the benefit of being able to disable theming on this one specific section.

2025-02-13 13:44 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +      lighten(@surface0, 5%)
We don't need to darken shades, rather we should use a lighter or darker existing shade - base or surface1.

2025-02-13 13:44 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +    @navmenu();
Why does this need to be a mixin?

2025-02-13 13:44 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +    }
Let's move this back up to the top beneath the `color-scheme:` setting like we do in all other userstyles.

2025-02-13 13:44 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +    }
Same here, let's move this back up to the top beneath the selection color setting.

2025-02-13 13:44 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +          filter: brightness(if((@flavor = latte), 100%, 130%));
Can we use a filter from @catppuccin-filters?

2025-02-13 13:44 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +        }
Do we need to set all of these properties? Padding, line height, etc? Can we use filters here instead?

2025-02-13 13:44 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +        filter: invert(100%);
Can we use this commented out SVG or at least a @catppuccin-filters filter?

2025-02-13 20:39 UTC, pynappo commented on styles/canvas-lms/catppuccin.user.less
> +@var checkbox styleNavMenu "Style navigation menu" 1
I originally had it because I liked being able to differentiate easier between colleges (I started this when I was enrolled in a community college and a 4-year college at the same time) but in hindsight, the different logos should be enough to do this anyways.

2025-02-13 20:40 UTC, pynappo commented on styles/canvas-lms/catppuccin.user.less
> +    @navmenu();
I was copying the last pattern shown in https://lesscss.org/features/#css-guards-feature and didn't know what the cleanest way to write this was, TBH

2025-02-13 20:43 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +    @navmenu();
It does look like this method is the very last thing, noted at the end of that section 😅 generally we prefer the syntax using the `when` keyword.

2025-02-18 16:38 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +        /* hack: to style only the background-image, we move the background-image to ::before and then tweak the styles */
```suggestion
        /* To style only the background-image, we move the background-image to ::before and then tweak the styles. */
```

2025-03-06 06:25 UTC, pynappo commented
i think this is good to go for now, lmk if anything else should be changed

2025-03-10 01:44 UTC, uncenter requested changes

2025-03-10 01:44 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +    --ic-brand-font-color-dark-lightened-30: lighten(@text, 30%);
Do we need to modify this color this much?

2025-03-10 01:44 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +      }
We should avoid setting this link color in the first place for this specific element rather than hard coding *their* hex code colors.

2025-03-10 01:44 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +        color: darken(@blue, 10%);
We could use sapphire or sky maybe?

2025-03-10 01:44 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +      background: darken(@red, 10%);
Can we use maroon here maybe instead of darkening red?

2025-03-10 01:44 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +      background-color: darken(@base, 5%);
Mantle?

2025-03-10 01:44 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +      }
Can we use subtext0/1 instead of fading text?

2025-03-10 01:44 UTC, uncenter commented on styles/canvas-lms/catppuccin.user.less
> +      background-color: fade(#e5f2f8, 20%);
Why are we fading a hard coded color?

2025-03-10 11:31 UTC, pynappo commented on styles/canvas-lms/catppuccin.user.less
> +        color: darken(@blue, 10%);
decided to remove instead, normal canvas doesn't bother with darkening hovered links

2025-03-10 11:35 UTC, pynappo commented on styles/canvas-lms/catppuccin.user.less
> +      background-color: fade(#e5f2f8, 20%);
probably i forgot to change the base color

2025-03-11 19:57 UTC, uncenter approved these changes
I don't want to bog down this massive improvement any more than I already have - LGTM!

2025-03-11 20:02 UTC, merged