refactor(nixos.wiki): switch to wiki.nixos.org
catppuccin/userstyles pull request #1125
Opened 2024-07-25 20:02 UTC by somerand0mcat

## 🔧 What does this fix? 🔧
as said in the title
![image](https://github.com/user-attachments/assets/c685009e-60a3-4e2e-9110-b6c34b021431)

## 🗒 Checklist 🗒

- [X] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [X] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

2024-07-25 20:04 UTC, uncenter requested changes

2024-07-25 20:04 UTC, uncenter commented on styles/nixos.wiki/README.md
Don't generate the auto-generated files please.

2024-07-25 20:05 UTC, somerand0mcat commented on styles/nixos.wiki/README.md
i didnt generate the file

2024-07-25 20:07 UTC, uncenter commented on styles/nixos.wiki/README.md
Look at the first line of that README file.

2024-07-25 20:07 UTC, somerand0mcat commented on styles/nixos.wiki/README.md
oh

2024-07-25 20:08 UTC, somerand0mcat commented on styles/nixos.wiki/README.md
i guess i'll just leave the readme file alone

2024-07-25 20:08 UTC, uncenter commented on styles/nixos.wiki/README.md
Update the userstyles.yml file, and rename this userstyle's directory.

2024-07-25 21:05 UTC, uncenter commented on scripts/userstyles.yml
> +  nixos-wiki:
Also update the URL below.

2024-07-25 21:11 UTC, somerand0mcat commented
btw, im not going to respond to anything in the PR untill tomorrow because i dont have much time so feel free to add the "waiting for author" label

2024-07-26 08:13 UTC, isabelroses commented
Some issuess on the revisions page: https://wiki.nixos.org/w/index.php?title=NixOS_Wiki&action=history
![image](https://github.com/user-attachments/assets/36aea364-6b97-4c93-ae86-ecf09762a7e8)

Some readablity and unthemed sections here: https://wiki.nixos.org/wiki/Special:WhatLinksHere/NixOS_Wiki
![image](https://github.com/user-attachments/assets/7599bb9c-d7ab-45ab-a3cf-a2a5c86a1ea1)

Can we import a syntax highlighting from somewhere? see code example: https://wiki.nixos.org/wiki/Cheatsheet

The login page
![image](https://github.com/user-attachments/assets/60a9dfb3-1bcd-4c17-b055-5ecbc09217e7)

2024-07-26 08:17 UTC, somerand0mcat commented
isn't syntax highlighting already themed?

2024-07-26 08:34 UTC, isabelroses commented
> isn't syntax highlighting already themed?

not as far as i can see, viewing https://wiki.nixos.org/wiki/Cheatsheet

2024-08-08 09:04 UTC, isabelroses approved these changes

2024-08-08 11:00 UTC, somerand0mcat commented
im going to rewrite this port again because the previous code from 2 weeks ago doesn't look good to me

2024-08-08 12:32 UTC, somerand0mcat commented
i was going to update/rewrite some parts of this userstyle because there were a bunch of unthemed stuff but i decided not to because it's really hard to code, theres alot of things that are hard to theme (e.g search bar, account preferences, etc)

2024-08-08 12:32 UTC, closed without merging