feat(roblox): init
catppuccin/userstyles pull request #1176
Opened 2024-08-08 10:19 UTC by GenShibe

so i made a bunch of changes, and they do not seem to be appearing on the existing PR. So i have been advised by bell to open a new PR

2024-08-08 12:36 UTC, somerand0mcat requested changes
can you theme this error message?
![image](https://github.com/user-attachments/assets/91603f8e-3b69-4bf7-8df6-2585432a2ca6)

2024-08-08 18:42 UTC, GenShibe commented
> can you theme this error message? ![image](https://private-user-images.githubusercontent.com/147266582/356223645-91603f8e-3b69-4bf7-8df6-2585432a2ca6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNDI4MTYsIm5iZiI6MTcyMzE0MjUxNiwicGF0aCI6Ii8xNDcyNjY1ODIvMzU2MjIzNjQ1LTkxNjAzZjhlLTNiNjktNGJmNy04ZGY2LTI1ODU0MzJhMmNhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxODQxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Njk0ZmU5MGI1ZjU5MDJkNmVmMDI5Njc5ZTc4NjgyY2Y1ZWMyNjg0MzNkZTFmODE2ZjcwNDcwYzQzMzUzOWMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qt18VyTbrL16yiq-KaBGvFyKc5R-0umREsUGcCSGV2I)

i'll see what i can do

2024-08-13 07:28 UTC, isabelroses reviewed
Cookie popup on login page (i see there are 2 login pages...)
![image](https://github.com/user-attachments/assets/95719216-95ba-42a2-abbb-30d5cc6b39a8)

Other then that seems good

2024-08-13 07:28 UTC, isabelroses commented on scripts/userstyles.yml
> +    current-maintainers: [*genshibe]
include `thatoneunoriginal` as a previous maintainer. I don't want them to go creditless for a PR you based off of.

2024-08-13 08:51 UTC, GenShibe commented
> Cookie popup on login page (i see there are 2 login pages...) ![image](https://private-user-images.githubusercontent.com/71222764/357314398-95719216-95ba-42a2-abbb-30d5cc6b39a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzkzMzUsIm5iZiI6MTcyMzUzOTAzNSwicGF0aCI6Ii83MTIyMjc2NC8zNTczMTQzOTgtOTU3MTkyMTYtOTViYS00MmEyLWFiYmItMzBkNWNjNmIzOWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA4NTAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNzRlYjlhMzgyYjJkN2IzZGU3MzI4MmMwMmJkNmY1NTQ0OThmZmQ4OTMwZDZjZTQ2ZTA5M2VlMjFhZDI0YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-WpK1ekXPgql-__ATj_ioDcuGLRWFaabk7wYHRLGJsQ)
> 
> Other then that seems good

cannot seem to find this...

2024-08-13 09:19 UTC, isabelroses submitted a review, later dismissed
As far as i can see LGTM

2024-08-13 09:54 UTC, ghost requested changes
the search bar border/suggestions is still unthemed
![image](https://github.com/user-attachments/assets/b13ff234-bfa0-440e-a22f-9e24832fed09)

2024-08-13 18:18 UTC, GenShibe commented
> the search bar border/suggestions is still unthemed ![image](https://private-user-images.githubusercontent.com/147266582/357364520-b13ff234-bfa0-440e-a22f-9e24832fed09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NzMyMjQsIm5iZiI6MTcyMzU3MjkyNCwicGF0aCI6Ii8xNDcyNjY1ODIvMzU3MzY0NTIwLWIxM2ZmMjM0LWJmYTAtNDQwZS1hMjJmLTllMjQ4MzJmZWQwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxODE1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Nzk4N2FmN2EzM2MxNDJhNjExYjM4NzRlYzViZTdkNzI0Y2VjODQxYzFhZjM2ZGQ0OWZiY2UzZjI3ZjkwMmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gLy98Gjnm63L4pGSLRUOV9pmROR_S2jUW1KvauyBQrM)

fixed this

2024-08-13 20:00 UTC, somerand0mcat approved these changes

2024-08-14 14:56 UTC, uncenter reviewed
Off of the preview alone, can we make the stuff in the primary buttons (like the play button one) crust instead of text?

![CleanShot 2024-08-14 at 16 56 26](https://github.com/user-attachments/assets/b091142c-6985-4323-8f04-a0d2d3ff37d5)

2024-08-16 08:27 UTC, GenShibe commented
> Off of the preview alone, can we make the stuff in the primary buttons (like the play button one) crust instead of text?
> 
> ![CleanShot 2024-08-14 at 16 56 26](https://private-user-images.githubusercontent.com/47499684/357875223-b091142c-6985-4323-8f04-a0d2d3ff37d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTcxMDQsIm5iZiI6MTcyMzc5NjgwNCwicGF0aCI6Ii80NzQ5OTY4NC8zNTc4NzUyMjMtYjA5MTE0MmMtNjk4NS00MzIzLThmMDQtYTBkMmQzZmYzN2Q1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA4MjY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2Zjg4ODBmMGE3MGVkODQ4N2YwYmI0ZjdlYWY2YzRmMmNiYWQ4MTM1ODI3YmM5YzdiZmFmNTYwZmVmMDNmMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MZlCIZW9ESxzPu6IHinfYBT_GX6qXX6K6gqBL7cTa_s)

i haven't changed the preview lol, but i'll get right onto that 🫡

2024-08-16 08:36 UTC, somerand0mcat commented
one last thing, can you fix the border in the search bar?
![image](https://github.com/user-attachments/assets/47619260-614f-40d3-ae70-9640081ec299)

2024-08-16 08:53 UTC, GenShibe commented
> one last thing, can you fix the border in the search bar? ![image](https://private-user-images.githubusercontent.com/147266582/358522789-47619260-614f-40d3-ae70-9640081ec299.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTc2NzEsIm5iZiI6MTcyMzc5NzM3MSwicGF0aCI6Ii8xNDcyNjY1ODIvMzU4NTIyNzg5LTQ3NjE5MjYwLTYxNGYtNDBkMy1hZTcwLTk2NDAwODFlYzI5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwODM2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDU1YTRjNGRhY2Q1ODQ3YzlhYWE1MTA5YjA2ZTVmZjdkN2EwZjI1YTA5ZWQwNzA3NDI1MzBjM2VkYTA2MWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o6iewTydjOsKBkKbnc8DrrvVm-1vOoYCQrL6v2pItls)

i'll see what i can do

2024-08-16 08:55 UTC, somerand0mcat commented
> i'll see what i can do

@GenShibe thanks :)
also im not going to look into your PR anymore after you've fixed the search bar because i have way more stuff to do outside catppuccin

2024-08-16 09:01 UTC, GenShibe commented on styles/roblox/preview.webp
updated the preview 🫡

2024-08-18 15:21 UTC, isabelroses submitted a review, later dismissed

2024-09-03 11:21 UTC, uncenter requested changes
The button styles don't match here (login page):
| Before | Themed |
| --- | --- |
| ![CleanShot 2024-09-03 at 07 20 11@2x](https://github.com/user-attachments/assets/8bae6707-0fdc-4f9d-b1e8-1c7bfae654d5)| ![CleanShot 2024-09-03 at 07 20 07@2x](https://github.com/user-attachments/assets/3478c752-6ede-4749-8e93-43f49bb9db28) |

2024-09-03 19:29 UTC, GenShibe commented
> The button styles don't match here (login page):
> 
> Before	Themed
> ![CleanShot 2024-09-03 at 07 20 11@2x](https://github.com/user-attachments/assets/8bae6707-0fdc-4f9d-b1e8-1c7bfae654d5)	![CleanShot 2024-09-03 at 07 20 07@2x](https://github.com/user-attachments/assets/3478c752-6ede-4749-8e93-43f49bb9db28)

will fix 🫡

2024-09-03 19:34 UTC, GenShibe commented
<img width="482" alt="image" src="https://github.com/user-attachments/assets/db6796b8-409e-4473-98fa-1374ab6be432">
does this look good to y'all?

2024-09-07 18:12 UTC, uncenter requested changes
Signup button is invisible when disabled and when not disabled.

![CleanShot 2024-09-07 at 14 03 28](https://github.com/user-attachments/assets/9b875f6f-ccc8-4e96-a963-38885ccc9d8f)

![CleanShot 2024-09-07 at 14 05 11](https://github.com/user-attachments/assets/4311e42b-5288-466d-8a68-3fe9a6248ed7)

![CleanShot 2024-09-07 at 14 07 03](https://github.com/user-attachments/assets/0351f3d3-e010-45fb-b785-86282c489730)

Toggle buttons that are *turned off* are unthemed:

![CleanShot 2024-09-07 at 14 09 09](https://github.com/user-attachments/assets/57b5367e-16f2-4890-9049-068e634337ef)

`.input-group .input-field` (inputs like the search bar in header, marketplace search bar) have an unthemed border.

Play button on games not accent/themed:

![CleanShot 2024-09-07 at 14 11 39](https://github.com/user-attachments/assets/d65347d0-d7bf-475f-8922-98fe1477d775)

Game loading / game modal has unthemed SVG roblox logo:

![CleanShot 2024-09-07 at 14 12 02](https://github.com/user-attachments/assets/586d9a59-a87b-4303-8790-51e349ae950c)

2024-09-20 11:02 UTC, uncenter commented
These settings buttons look better, but the hover states don't match the regular appearance of the buttons. Try to match the hover state change to how Roblox itself shows the hover state - in some cases that is filling in the button and inverting text color (though with text, not accent), in some cases it is making the button border/text brighter/darker shade, etc.
![CleanShot 2024-09-20 at 06 58 47](https://github.com/user-attachments/assets/48501b77-63f4-4497-aae7-85bcbce4964e)

2024-09-20 11:04 UTC, uncenter requested changes

2024-09-20 11:04 UTC, uncenter commented on styles/roblox/catppuccin.user.css
> +        @svg: escape('<svg width="56" height="812" viewBox="0 0 56 812" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M15.25 3h-2.5A3.25 3.25 0 0 0 9
This is a super bright border color for these!

2024-09-20 11:04 UTC, uncenter commented on styles/roblox/catppuccin.user.css
> +        @svg: escape('<svg width="56" height="812" viewBox="0 0 56 812" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M15.25 3h-2.5A3.25 3.25 0 0 0 9
![CleanShot 2024-09-20 at 07 03 00](https://github.com/user-attachments/assets/52901704-cd64-41d3-bfae-0afcc9cfbcfc)

Looks weird with this hover state.

2024-09-25 01:23 UTC, uncenter commented
Thanks for your work on this - I think we can call it good enough at this point, if you can get the linter happy!

2024-10-12 22:27 UTC, isabelroses approved these changes, later dismissed

2024-10-17 10:58 UTC, isabelroses approved these changes, later dismissed

2024-10-17 11:22 UTC, uncenter requested changes
This banner thing (`.home-page-upsell-card-banner-container`) I'm getting is unthemed, just needs the background and border color fixed.

![CleanShot 2024-10-17 at 07 18 07](https://github.com/user-attachments/assets/e8f0e27d-6983-41d3-847c-50d0074e4d9c)

When like looking at your profile themed vs unthemed it looks weird in that it has a lot of patches with different background colors, not matching the solidness/single color of the unthemed website. 
The cancel and save buttons on your profile are also somewhat unthemed:

![CleanShot 2024-10-17 at 07 20 33](https://github.com/user-attachments/assets/02ec4000-259d-4b49-833d-16a997035639)

Top area of marketplace unthemed:

![CleanShot 2024-10-17 at 07 21 26](https://github.com/user-attachments/assets/b75a8b5e-22c8-431b-9ede-78e66ee65090)

In general please just go through and click around the website and fix the obvious unthemed / bad looking areas.

2024-10-22 11:22 UTC, uncenter commented
![CleanShot 2024-10-22 at 07 19 51](https://github.com/user-attachments/assets/31d06a91-0785-4819-8fe4-bace16227a90)

Sidebar unthemed.

![CleanShot 2024-10-22 at 07 20 17](https://github.com/user-attachments/assets/ed708184-172b-4a4a-bb08-609b1e7f744b)

Notifications window.

> When like looking at your profile themed vs unthemed it looks weird in that it has a lot of patches with different background colors, not matching the solidness/single color of the unthemed website. The cancel and save buttons on your profile are also somewhat unthemed:
> 
> ![CleanShot 2024-10-17 at 07 20 33](https://private-user-images.githubusercontent.com/47499684/377441091-02ec4000-259d-4b49-833d-16a997035639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTYyODAsIm5iZiI6MTcyOTU5NTk4MCwicGF0aCI6Ii80NzQ5OTY4NC8zNzc0NDEwOTEtMDJlYzQwMDAtMjU5ZC00YjQ5LTgzM2QtMTZhOTk3MDM1NjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDExMTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5YTZjY2Y5ZWViYWMyNzE4ZGRlOTU4MDA1NjQ3ZjA3NDcyYzE5NDYzNDEwMjZlMzI3NzNmMzliZjRiMjE3N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pOT15lNloGuJqj_bUEhHNClSh8fau_amuz4wvlYpjow)

Neither of these are fixed as far as I can tell.

2024-11-10 18:24 UTC, uncenter commented
Buttons on https://www.roblox.com/bundles/43/Toy-Animation-Pack don't have the correct hover states:

![CleanShot 2024-11-10 at 13 22 31](https://github.com/user-attachments/assets/b7470860-1e04-40de-9ae4-3957a6d9c8a0)

https://www.roblox.com/upgrades/robux

This page could have some minor improvements in background color and text.

And the notifications window and profile page from my last two comments are not fixed either.

2024-11-10 19:01 UTC, GenShibe commented
> Buttons on https://www.roblox.com/bundles/43/Toy-Animation-Pack don't have the correct hover states:
> 
> 
> 
> ![CleanShot 2024-11-10 at 13 22 31](https://github.com/user-attachments/assets/b7470860-1e04-40de-9ae4-3957a6d9c8a0)
> 
> 
> 
> https://www.roblox.com/upgrades/robux
> 
> 
> 
> This page could have some minor improvements in background color and text.
> 
> 
> 
> And the notifications window and profile page from my last two comments are not fixed either.

can't seem to replicate the profile page issues oddly enough, and im pretty sure that i fixed the notif window... i'll take a look

2024-11-10 21:10 UTC, uncenter commented
LMK when everything is fixed.

2025-03-11 20:12 UTC, uncenter commented
Closing as stale. Due to the large and complicated nature of this userstyle I won't say "feel free" to pick this up and continue work on it if anyone is interested, but the possibility is there still 😅

2025-03-11 20:12 UTC, closed without merging

2025-03-19 04:42 UTC, WalkQuackBack commented
I was looking around here for some things to pick up: some of the components that were originally themed here now seem to use a fork of MUI named UIBlox/WebBlox/Foundation which from a glance look like they use generated class names at best and inline CSS at worse, making them a headache to theme. 
![Screenshot_2025-03-18-22-23-01-844_com microsoft emmx canary-edit](https://github.com/user-attachments/assets/02fb1dce-258b-4752-b26a-cd94af9afb19)

I also saw a parallax banner on the home page at some point but it doesn't seem to be there at the moment.

This Stripe (embed?) might be a bit hard to theme, especially if it's an iframe
![Screenshot_2025-03-18-22-27-54-692_com microsoft emmx canary-edit](https://github.com/user-attachments/assets/739fd7ca-2391-40a6-8a35-b31a2320fd46)

Also, there's a scope question to be asked: Will this just include the base Roblox website, or will it also include the entire Creator Hub which uses WebBlox almost everywhere along with the generated class names.

This [forum post]( https://devforum.roblox.com/t/do-not-use-embedded-react-component-styling-in-uiblox-andor-add-html-element-classes-ids-and-metadata/2277306) looks like it tracks this exact issue, so it might be best to show support there.