feat(netscape): init
catppuccin/userstyles pull request #1235
Opened 2024-08-24 22:53 UTC by NeonGamerBot-QK

## 🎉 Theme for netscape 🎉

an old netscape site with news.
## 💬 Additional Comments 💬
images are currently unthemed and have no idea how to theme them atm.
Ill generate preview before merge.

## 🗒 Checklist 🗒

- [X] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [X] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [X] I have ensured that the new directory is in **lower-kebab-case**.
  - [X] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [X] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/scripts/userstyles.yml)
      file with information about the new userstyle.
- [X] I have included the following files:
  - [X] `catppuccin.user.css` - all the CSS for the userstyle, based on the
        template.
  - [ ] `preview.webp` - composite image of all four individual flavor screenshots (taken with the default accent color of mauve) stitched together, generated via [Catwalk](https://github.com/catppuccin/catwalk).

2024-08-25 02:11 UTC, uncenter requested changes
Some comments about metadata and extra comments, but in general with the main styling I'm seeing a lot of unorganized classes grouped together arbitrarily, and lots of selectors without comments that don't make it clear what they theme (e.g. `#hdrLf`). I'd recommend you look through existing userstyles to see how me and other authors/maintainers keep userstyles organized, be it top to bottom of the page (header, body, then footer), or by basic elements first and more specific stuff further down, etc.

2024-08-25 02:11 UTC, uncenter commented on scripts/userstyles.yml
> +    name: netscape
```suggestion
    name: Netscape ISP
```

2024-08-25 02:11 UTC, uncenter commented on scripts/userstyles.yml
> +    color: text
```suggestion
    color: sapphire
```

2024-08-25 02:11 UTC, uncenter commented on styles/netscape/catppuccin.user.css
> +  */
Please delete these template comments after filling it out!
```suggestion
```

2024-08-25 02:11 UTC, uncenter commented on styles/netscape/catppuccin.user.css
> +  }
```suggestion
```

2024-08-25 02:34 UTC, NeonGamerBot-QK commented
> Some comments about metadata and extra comments, but in general with the main styling I'm seeing a lot of unorganized classes grouped together arbitrarily, and lots of selectors without comments that don't make it clear what they theme (e.g. `#hdrLf`). I'd recommend you look through existing userstyles to see how me and other authors/maintainers keep userstyles organized, be it top to bottom of the page (header, body, then footer), or by basic elements first and more specific stuff further down, etc.

i can try my best since i wrote half and then imported the other half. (also cause they are all short-worded classNames/ID's)

2024-08-25 02:42 UTC, uncenter commented
Make sure to update that metadata as well with the name change.

2024-09-06 12:51 UTC, NeonGamerBot-QK commented
@uncenter  any updates?

2024-09-06 13:01 UTC, uncenter requested changes
Looking very messy overall. Lots of random newlines separating content for no reason, commented out code, a lot of `div.xyz` for whatever reason - just use `.xyz` if it is clear by the classname/ID. Also please format it with Prettier (format on save is a godsend, use it).

2024-09-06 13:06 UTC, NeonGamerBot-QK commented
ignore the review request it was a missclick

2024-09-06 14:36 UTC, uncenter commented on styles/netscape/catppuccin.user.css
> -
This whitespace is in the template, and is required for *aesthetics* and consistency.

2024-09-06 14:36 UTC, uncenter commented on styles/netscape/catppuccin.user.css
> -
Same with all this

2024-11-03 19:11 UTC, NeonGamerBot-QK commented
Any updates?

2025-02-02 16:00 UTC, isabelroses reviewed
Thanks for the PR. But we have decided to reject the application due to the limited user base of this site and the growing size of userstyles. Thanks for your time and effort.

2025-02-02 16:00 UTC, closed without merging

2025-02-02 18:15 UTC, NeonGamerBot-QK commented
all good :3