feat(nodejs): init
catppuccin/userstyles pull request #1246
Opened 2024-08-30 20:54 UTC by nikitarevenco

## 🎉 Theme for [NodeJS](https://nodejs.org)🎉

NodeJS is a javascript runtime, the nodejs website includes docs for it

## 💬 Additional Comments 💬

Difficulties 

Right-clicking on these breadcrumbs applies a green background and at the moment I dont know how to remove it. none of the pseudoclasses work and it doesn't gain any additional class.

Same behaviour can be observed in a few different places, if i can figure out how to fix it here I'll probably be able to fix it in those places too
![image](https://github.com/user-attachments/assets/88a6e819-d451-4321-9da7-401424fc3091)

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/scripts/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - [x] `catppuccin.user.css` - all the CSS for the userstyle, based on the
        template.
  - [x] `preview.webp` - composite image of all four individual flavor screenshots (taken with the default accent color of mauve) stitched together, generated via [Catwalk](https://github.com/catppuccin/catwalk).

2024-08-30 21:01 UTC, uncenter requested changes

2024-08-30 21:01 UTC, uncenter commented on styles/nodejs/catppuccin.user.css
> +        }
Try to use nesting when possible: https://lesscss.org/features/#parent-selectors-feature.

2024-08-30 21:01 UTC, uncenter commented on styles/nodejs/catppuccin.user.css
> +        }
Nesting would work great here as well.

2024-08-30 21:01 UTC, uncenter commented on scripts/userstyles.yml
> +    color: mauve
```suggestion
    icon: nodedotjs
    color: green
```

2024-08-30 21:03 UTC, uncenter commented
I should note that the Node.js documentation, like the website, has a redesign in the works: https://togithub.com/nodejs/node/issues/52343.

2024-08-30 21:15 UTC, nikitarevenco commented
> I should note that the Node.js documentation, like the website, has a redesign in the works: https://togithub.com/nodejs/node/issues/52343.

Oh thanks for letting me know! I've looked at that issue and looks like they're changing the design quite significantly 
![image](https://github.com/user-attachments/assets/322ae2d2-cfd8-410a-85e6-d53a63dbfd00)


And looks like over the months they have been making steady progress with it. I'll just wait until they deploy the new docs then I'll rework this PR. Is that fine? We can keep it as draft in the meantime?

2024-08-30 23:52 UTC, uncenter commented
I mean I'm okay merging with the current state assuming it correctly themes the existing docs! Up to you.

2025-03-11 20:18 UTC, uncenter commented
I should also say no pressure to continue work on this if you aren't interested. If you still are, I would also ask that you update this new userstyle to match the new template for new userstyles that we made some major changes to in December/January (#1546).

2025-03-11 20:42 UTC, nik-rev commented
Ok, if I decide to continue this I feel like it would just make sense to start from scratch

2025-03-11 20:42 UTC, closed without merging