feat(indie-wiki-buddy): init
catppuccin/userstyles pull request #1251
Opened 2024-09-01 21:51 UTC by thismoon

## 🎉 Theme for [Indie Wiki Buddy](https://getindie.wiki/) 🎉

Indie Wiki Buddy is a browser extension/addon that automatically redirects from wikis to independent wikis
e.g. https://minecraft.fandom.com/wiki/Minecraft_Wiki -> https://minecraft.wiki/w/Minecraft_Wiki
it can be configured to change the behavior to not redirecting and showing a banner instead
![image](https://github.com/user-attachments/assets/19d0b966-aaf4-4796-85bf-ad2fee6008fd)
it can also automatically redirect fandom wikis to a chosen [BreezeWiki](https://breezewiki.com/) instance (an alternate front end for fandom without ads etc) (in case there isn't an independent wiki version of that wiki)
it also can hide or replace Fandom/Fextralife/Neoseeker links in search results in several search engines:
- duckduckgo
![image](https://github.com/user-attachments/assets/b630d8f9-aa57-4153-86f1-15f75dac3247)
- google
![image](https://github.com/user-attachments/assets/1184df78-f84b-4a1a-ac61-dab6ed1f64fc)
- bing
![image](https://github.com/user-attachments/assets/41438436-b86a-49aa-8ca6-38d3b5f1376f)
- qwant
![image](https://github.com/user-attachments/assets/a4ad5629-2fd5-45d1-bc24-f1c856efd49f)
- startpage
![image](https://github.com/user-attachments/assets/946f0665-c33e-4824-a63c-5a4e0232a198)
- yahoo
![image](https://github.com/user-attachments/assets/ce88625a-4c6a-40b4-aa51-5ac0137b90ac)
- yandex
![image](https://github.com/user-attachments/assets/1f9656c2-aac3-4e2d-bfd4-dee88bac4976)
- brave search
![image](https://github.com/user-attachments/assets/07cb4036-b967-4cb4-8259-fce36a32cf9b)
- ecosia
![image](https://github.com/user-attachments/assets/b9ac1f27-e48c-4d98-9564-2867d7a300ce)
- kagi
i am not going to pay to use a search engine ![KEKW](https://cdn.discordapp.com/emojis/955499372760694906.webp?size=48&quality=lossless)

## 💬 Additional Comments 💬

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/scripts/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - [x] `catppuccin.user.css` - all the CSS for the userstyle, based on the
        template.
  - [x] `preview.webp` - composite image of all four individual flavor screenshots (taken with the default accent color of mauve) stitched together, generated via [Catwalk](https://github.com/catppuccin/catwalk).

2024-09-02 18:44 UTC, isabelroses submitted a review, later dismissed

2024-09-14 23:40 UTC, uncenter requested changes

2024-09-14 23:40 UTC, uncenter commented on styles/indie-wiki-buddy/catppuccin.user.css
> +    /* Start styling your website here: */
```suggestion
```

2024-09-14 23:40 UTC, uncenter commented on styles/indie-wiki-buddy/catppuccin.user.css
> +    }
```suggestion
    .iwb-new-link button {
      color: @base;
      background: @blue;
      &:hover {
        background: @sky;
      }
    }
```

2024-09-14 23:40 UTC, uncenter commented on styles/indie-wiki-buddy/catppuccin.user.css
> +curl -s https://raw.githubusercontent.com/KevinPayravi/indie-wiki-buddy/main/manifest-firefox.json | python -c "import sys, json;print(*json.loads(sys.stdin.read())['content_scripts'][2]['matches'],
```suggestion
To get a list of supported search engines, run the following command:
curl -s https://raw.githubusercontent.com/KevinPayravi/indie-wiki-buddy/main/manifest-firefox.json | python -c "import sys, json;print(*json.loads(sys.stdin.read())['content_scripts'][2]['matches'], sep='\n')"
```

2024-09-14 23:40 UTC, uncenter commented on styles/indie-wiki-buddy/catppuccin.user.css
> +// wiki banners
```suggestion
```

2024-09-14 23:40 UTC, uncenter commented on styles/indie-wiki-buddy/catppuccin.user.css
> +    }
```suggestion
    .indie-wiki-banner-link {
      color: @blue;

      &:hover {
        color: @sky;
      }
    }
    .indie-wiki-banner-disabled {
      color: @subtext0;
    }
```

2024-09-14 23:40 UTC, uncenter commented on styles/indie-wiki-buddy/preview.webp
I mean this screenshot is 98% of our DuckDuckGo port. Can we get a screenshot of the banner element instead?

2024-09-15 18:03 UTC, thismoon commented on styles/indie-wiki-buddy/preview.webp
i followed what the [Shinigami Eyes port](https://github.com/catppuccin/userstyles/tree/main/styles/shinigami-eyes) did. but i will make another screenshot later then

2024-09-15 18:33 UTC, uncenter commented on styles/indie-wiki-buddy/catppuccin.user.css
> +// wiki banners
Because it's a redundant comment, all the classes are about wiki banners and you can read the domain names.

2024-10-27 22:27 UTC, comfysage approved these changes

2024-11-11 03:34 UTC, uncenter approved these changes

2024-11-11 11:02 UTC, isabelroses approved these changes

2024-11-11 11:03 UTC, merged