chore(tree-wide): add missing `:root` to 9 styles
catppuccin/userstyles pull request #1302
Opened 2024-09-13 14:51 UTC by thismoon

## 🔧 What does this fix? 🔧

userstyles that depend on the user's system theme use this snippet from the template style:
```less
  @media (prefers-color-scheme: light) {
    :root {
      #catppuccin(@lightFlavor, @accentColor);
    }
  }
  @media (prefers-color-scheme: dark) {
    :root {
      #catppuccin(@darkFlavor, @accentColor);
    }
  }
```
however some userstyles doesn't have the `:root` part which results in the selection background color not working

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [x] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

2024-09-13 15:30 UTC, isabelroses requested changes

2024-09-13 15:30 UTC, isabelroses commented on styles/pinterest/catppuccin.user.css
Can you revert this file, changes here seem to be breaking the style.

2024-09-13 15:43 UTC, thismoon commented on styles/pinterest/catppuccin.user.css
i found a way to fix the selection without breaking the style (https://github.com/catppuccin/userstyles/pull/1302/commits/ac8061bafa1da676256dac794d21479c5ebdd3b0)
is it okay to keep the fix in this pr?

2024-09-13 16:21 UTC, isabelroses submitted a review, later dismissed

2024-09-13 16:43 UTC, uncenter commented on styles/pinterest/catppuccin.user.css
>      html {
Instead, change the selectors above to use `:root` like you have been, and replace the `html` here (and any other `html`s in this file) with `&`.

2024-09-13 17:11 UTC, Guaxinim5573 submitted a review, later dismissed

2024-09-13 19:26 UTC, uncenter approved these changes
Assuming you have tested each of these, looks good!

2024-09-14 05:37 UTC, AnubisNekhet approved these changes

2024-09-14 13:52 UTC, merged