feat(kotlin): init
catppuccin/userstyles pull request #1309
Opened 2024-09-14 21:30 UTC by thelooter

## 🎉 Theme for [Kotlin](https://kotlinlang.org/) 🎉

![preview](https://github.com/user-attachments/assets/89c26f6f-b549-49ff-9a07-1c21f588e4ba)

The Kotlin website offers resources for learning and using Kotlin, a modern, multiplatform programming language. It highlights Kotlin's key features, including simplicity, Java compatibility, and usage across platforms like Android, web, and server-side development.

## 💬 Additional Comments 💬

The website doesn't offer an official light mode, therefore latte support needs to be selected via the dark mode menu.

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/scripts/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - [x] `catppuccin.user.css` - all the CSS for the userstyle, based on the
        template.
  - [x] `preview.webp` - composite image of all four individual flavor screenshots (taken with the default accent color of mauve) stitched together, generated via [Catwalk](https://github.com/catppuccin/catwalk).

2024-09-14 21:42 UTC, uncenter commented on styles/kotlin/catppuccin.user.css
> +  */
```suggestion
```

2024-09-14 21:47 UTC, uncenter requested changes

2024-09-14 21:47 UTC, uncenter commented on styles/kotlin/catppuccin.user.css
> +  }
```suggestion
```
They do have a `.theme-light` class but I don't see a way of toggling it.

2024-09-14 21:47 UTC, uncenter commented on styles/kotlin/catppuccin.user.css
> +    }
Please don't remove, move, or change the default styles:
https://github.com/catppuccin/userstyles/blob/88f5177d579587655a4291752f3d9690d5169471/template/catppuccin.user.css#L78-L89

2024-09-14 21:47 UTC, uncenter commented on styles/kotlin/catppuccin.user.css
> +    }
Move to default styles section.

2024-09-14 21:47 UTC, uncenter commented on styles/kotlin/catppuccin.user.css
> +    --wh-color-success-t40: darken(@green, 50%);
These seem realllllyyyy dark. Use fade if you have to, or limit light/darkening to 5-15%.

2024-09-14 21:47 UTC, uncenter commented on styles/kotlin/catppuccin.user.css
> +    }
Self reminder for https://github.com/catppuccin/prismjs/issues/2.

2024-09-14 21:47 UTC, uncenter commented on styles/kotlin/catppuccin.user.css
> +
```suggestion
```

2024-09-14 21:47 UTC, uncenter commented on styles/kotlin/catppuccin.user.css
> +/* prettier-ignore */
As the comment says, this should not be formatted! Please reset to the condensed block used in the template.

2024-09-20 00:41 UTC, uncenter commented on styles/kotlin/catppuccin.user.css
> +
No point in importing this with the difference in classnames.

2024-10-03 02:20 UTC, uncenter requested changes
Hover text of nav subitems is unthemed.

![CleanShot 2024-10-02 at 22 10 01](https://github.com/user-attachments/assets/e8c2b466-b1e7-47d9-bd2b-4b0397f0e18e)

Boxes with borders do not have correctly themed border colors on hover.

![CleanShot 2024-10-02 at 22 11 13](https://github.com/user-attachments/assets/93c82961-7b5d-443a-b2db-35e409596af0)

Line numbers, expand/hide buttons, open in playground text,and run button of code samples unthemed (https://kotlinlang.org/docs/basic-syntax.html#functions).

![CleanShot 2024-10-02 at 22 13 43](https://github.com/user-attachments/assets/298d69fe-3015-4f8d-a395-cfdde3910c63)

These note callouts have unthemed text (https://kotlinlang.org/docs/typecasts.html).

![CleanShot 2024-10-02 at 22 14 56](https://github.com/user-attachments/assets/77d9acbf-0a01-4787-ba42-de8883db7226)

Slashes in breadcrumbs unthemed.

![CleanShot 2024-10-02 at 22 15 59](https://github.com/user-attachments/assets/4f4abe4e-fdc1-4df1-bddb-6d8efbeeb27d)

Playground is actually mostly themed, just this toolbar and output box are not themed.

![CleanShot 2024-10-02 at 22 17 36](https://github.com/user-attachments/assets/14316466-9d9c-4925-97f2-102b3861ee9f)

Search box unthemed.

![CleanShot 2024-10-02 at 22 18 12](https://github.com/user-attachments/assets/e616bc19-1a9f-47a5-96aa-bc448c1798e0)

API docs are unthemed (the old styling - https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/ - looks bad, you could prob just theme the new https://kotlinlang.org/api/core/kotlin-stdlib/)

2024-11-16 20:55 UTC, uncenter commented
No need to force push FYI. Commit history in here doesn't matter since we squash merge all PRs.

2024-11-19 16:11 UTC, thelooter commented
> Just want to make sure I don't miss this - let me know if you are ready for me to re-review. If the previously mentioned issues are fixed we should be good to merge.

I have styled the old API Docs, the new ones are yet to be done. Will take a little bit more time

2025-02-01 02:38 UTC, uncenter commented
Buttons on was this page helpful at bottom of docs pages is unreadable until hover:

![CleanShot 2025-01-31 at 21 34 45](https://github.com/user-attachments/assets/fbd0b6ea-ba66-4b21-add9-61f89b944e9f)

Table of contents circles:

![CleanShot 2025-01-31 at 21 34 53](https://github.com/user-attachments/assets/1d185137-5ff9-4ec1-967a-fe544e6e0f7c)

The entire code block should be mantle, not just the syntax highlighting part:

![CleanShot 2025-01-31 at 21 35 01](https://github.com/user-attachments/assets/87b31984-f3bb-447f-a31c-f3581ac6a596)

Inline code background should be surface0 I think.

![CleanShot 2025-01-31 at 21 35 06](https://github.com/user-attachments/assets/ce809612-0815-45d4-942e-ac9971a8ce23)

Current page in sidebar on hover disappears:

![CleanShot 2025-01-31 at 21 38 04](https://github.com/user-attachments/assets/f52d0846-73e5-4e08-a9c1-e0bd78bb3502)

2025-04-18 20:19 UTC, uncenter commented
Closed due to lack of activity. Feel free to open as a new pull request if anyone is interested in continuing this userstyle.

2025-04-18 20:19 UTC, closed without merging