feat(fontawesome): init
catppuccin/userstyles pull request #1323
Opened 2024-09-17 23:08 UTC by trinkey

## 🎉 Theme for Font Awesome 🎉
An svg icon library that kinda sucks but not as much as their website's css

## 💬 Additional Comments 💬
- this websites uses variables. occasionally.
- sometimes inline styles redefine variables
- why are there so many inline styles
- the inline styles don't stop help

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/scripts/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - [x] `catppuccin.user.css` - all the CSS for the userstyle, based on the
        template.
  - [x] `preview.webp` - composite image of all four individual flavor screenshots (taken with the default accent color of mauve) stitched together, generated via [Catwalk](https://github.com/catppuccin/catwalk).

2024-09-17 23:44 UTC, trinkey commented
404 page isn't styled ughhhhhhhhhhhhhh

2024-09-18 00:39 UTC, sgoudham commented
Testing

2024-11-21 15:56 UTC, uncenter requested changes
Stuff on https://fontawesome.com/search?ip=classic&s=regular&o=r

<img width="412" alt="image" src="https://github.com/user-attachments/assets/332b6705-860f-4dc9-9717-f395b6837a17">

<img width="127" alt="image" src="https://github.com/user-attachments/assets/f1487693-57cb-48cf-abb8-9352ed52d191">

In modal on search page

<img width="157" alt="image" src="https://github.com/user-attachments/assets/995a135f-c2c8-4f0c-bc66-dbe208790b32">


<img width="151" alt="image" src="https://github.com/user-attachments/assets/ba34ac50-31b2-4db1-babe-e9715f2b7435">
(arrow buttons next/previous in modal)

https://docs.fontawesome.com/web/style/rotate:

<img width="754" alt="image" src="https://github.com/user-attachments/assets/2768bab8-12b4-4572-9ac9-d682e6595923">

(at bottom)
<img width="286" alt="image" src="https://github.com/user-attachments/assets/f7d4a6eb-4543-4b69-bee5-b21cd3e075e6">

(sidebar active item background)

https://docs.fontawesome.com/web/style/mask:

<img width="750" alt="image" src="https://github.com/user-attachments/assets/5ed3c744-f2c0-4e02-9da9-77368c1ad8e6">

https://docs.fontawesome.com/web/add-icons/upload-icons/icon-design:
<img width="745" alt="image" src="https://github.com/user-attachments/assets/cfa2d995-5d40-412a-b30f-b08a18511607">

Header and below text on https://docs.fontawesome.com/ (--sl-color-text-accent is unthemed)

2024-11-21 15:56 UTC, uncenter commented on scripts/userstyles.yml
> +    categories: ["development", "photo_and_video"]
```suggestion
    categories: [development]
```

2024-11-22 01:15 UTC, trinkey commented
i see your feedback and will work on fixing these things when i have time but i'm like really busy right now, i'll hopefully get these done by tomorrow or saturday

2024-11-25 01:16 UTC, trinkey commented
> i'll hopefully get these done by tomorrow or saturday

ill do it tomorrow i swear

2024-11-29 04:46 UTC, uncenter commented
FYI the linter is failing.

2024-12-24 18:10 UTC, uncenter requested changes
![CleanShot 2024-12-24 at 13 03 32](https://github.com/user-attachments/assets/3b923e99-c785-4fce-894b-f415cfa22588)

These codeblock tabs look inverted. The mantle color should be used for the code backgorund and inactive tabs, and the lighter color should be used for the active tab maybe?

2024-12-29 20:34 UTC, isabelroses requested changes
A few dark on dark buttons here.
![image](https://github.com/user-attachments/assets/93e0ed9f-0f27-4e4a-9b86-9822346b9bd0)
![image](https://github.com/user-attachments/assets/890c86ae-467e-472d-8002-b8f04b30e2aa)

We seem to have added our own backgrounds occasionally, which leads to wierd borders and strangely sized boxes.
![image](https://github.com/user-attachments/assets/0d8e8966-82b3-42c8-98fd-78c626710bef)

When an icon is `:active`, it goes invisable
![image](https://github.com/user-attachments/assets/04537200-f66c-4b5f-874d-2c8b00ec3239)

They also have code blocks, https://docs.fontawesome.com/apis/graphql/get-started, I do believe we have an expressive code port, well kind of https://github.com/expressive-code/expressive-code/blob/65e9b6b53936f53b147c1415a58d538e3aa3df35/docs/plugins/shiki-colorized-brackets/themes.js#L8 this is more of a in the future thing.

2024-12-30 04:53 UTC, trinkey commented
i'm not going to continue this style because the website is a hot mess and i don't "enjoy" (as much as you *can* enjoy writing css) theming it. might pick it up again but unlikely

2024-12-30 04:53 UTC, closed without merging