feat(gitlab): init
catppuccin/userstyles pull request #1337
Opened 2024-09-24 16:20 UTC by Thomas-Philippot

## 🎉 Theme for Gitlab 🎉
Gitlab is a online service to manage git repos with devops tools

## 💬 Additional Comments 💬

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/scripts/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - [x] `catppuccin.user.css` - all the CSS for the userstyle, based on the
        template.
  - [x] `preview.webp` - composite image of all four individual flavor screenshots (taken with the default accent color of mauve) stitched together, generated via [Catwalk](https://github.com/catppuccin/catwalk).

2024-09-24 16:26 UTC, uncenter requested changes

2024-09-24 16:26 UTC, uncenter commented on scripts/userstyles.yml
> +      app-link: "https://github.com"
```suggestion
      app-link: "https://gitlab.com"
```

2024-09-24 16:26 UTC, uncenter commented on scripts/userstyles.yml
> +    categories: [ development, productivity ]
```suggestion
    categories: [development, productivity]
```

2024-09-24 16:26 UTC, uncenter commented on scripts/userstyles.yml
> +    color: text
```suggestion
    color: peach
```
Please please please follow the directions! This should match the color of the brand on https://simpleicons.org/, so orange -> peach.

2024-09-24 16:26 UTC, uncenter commented on scripts/userstyles.yml
> +    current-maintainers: [ *thomas-philippot ]
```suggestion
    current-maintainers: [*thomas-philippot]
```

2024-09-24 16:30 UTC, uncenter commented
Lot of things still unthemed, please mark it as ready when you have fully themed the entire application - settings menus, modals, dropdown/selects/inputs, profile pages, READMEs, etc. A good trick is to use GitLab dark mode, but set the Catppuccin flavor to latte. Very easy to spot unthemed areas.

2024-09-24 16:34 UTC, Thomas-Philippot commented
Yes, still a couple of things to work on.
I just started working on this today, I'm making the pr to save my work, and mark this as work in progress

2024-09-24 16:36 UTC, uncenter commented on styles/github/README.md
Revert please.

2024-09-24 22:04 UTC, thelooter commented
I'm happy to help with this userstyle too if necessary

2024-09-25 10:59 UTC, Thomas-Philippot commented
> I'm happy to help with this userstyle too if necessary

I will be more than happy to have some help, how can we manage this ?

2024-09-25 11:06 UTC, Thomas-Philippot commented on styles/github/README.md
How can I revert and wich commit should i revert to ?

2024-09-25 11:11 UTC, thelooter commented
> > I'm happy to help with this userstyle too if necessary
> 
> I will be more than happy to have some help, how can we manage this ?

Are you in the discord server? Communicating there could make things a bit easier

2024-09-28 13:31 UTC, somerand0mcatt commented
> I'm happy to help with this userstyle too if necessary

same here, i'll help fix bugs for this userstyle for a little bit

2024-10-02 21:47 UTC, uncenter commented
What editor are you using where the file isn't recognized as Less?

2024-10-03 19:45 UTC, thelooter commented
> What editor are you using where the file isn't recognized as Less?

Webstorm. And if I manually reassign it to less it doesn't persist

2024-10-03 20:06 UTC, somerand0mcatt commented
> Webstorm. And if I manually reassign it to less it doesn't persist 

@thelooter try going to settings (or preferences) > editor > file types and you should be able to change it there

2024-10-03 20:18 UTC, uncenter commented
To add on to that, if there is a way to set that in a project local settings file (like .vscode/settings.json) we would be happy to accept a PR that introduces it here.

2024-10-06 06:32 UTC, somerand0mcatt commented
> To add on to that, if there is a way to set that in a project local settings file (like .vscode/settings.json) we would be happy to accept a PR that introduces it here. 

i've tried searching webstorm's docs and installing webstorm to try and to this but unfortunately, theres no way to do that

2024-12-24 10:12 UTC, Thomas-Philippot commented
Hi everyone, I've been using this branch for a couple of weeks now and I thinks its ok.
It might be good to talk about reviewing the PR.

2024-12-24 15:45 UTC, uncenter commented on styles/gitlab/preview.webp
This needs to be retaken.

2024-12-24 15:50 UTC, uncenter requested changes
- Various issues with the diff view on pull requests.
- Background color of code syntax highlighting for raw files.
- The 'repository graph' (e.g. https://gitlab.com/stephan-raabe/dotfiles/-/network/main).
- Hover on repo lists (e.g. https://gitlab.com/groups/stephan-raabe/-/inactive).

2024-12-24 16:35 UTC, thelooter commented
Colors on Security Dashboard:
![image](https://github.com/user-attachments/assets/753e7536-13df-499b-b1a8-186bd9a45a22)

Compliance Center Status:
![image](https://github.com/user-attachments/assets/c9f05536-7918-4706-bbb6-b5d91466b62f)

Readability on issue labels:
![image](https://github.com/user-attachments/assets/7a8a8cfd-b9c3-4964-ba36-43d4c6607d28)

Header on Security View in Pipeline:
![image](https://github.com/user-attachments/assets/bf95a760-4260-491f-8a38-91ff08c16d1f)

Repository > CI/CD Settings > Runner:
![image](https://github.com/user-attachments/assets/1e9bcc4c-dd62-44e0-9c11-b6211a03ed7f)

Repository > General Settings > Service Desk
![image](https://github.com/user-attachments/assets/321b4709-0c6f-4c8b-97a4-f3de9e3bd96f)

Instance Runner View:
![image](https://github.com/user-attachments/assets/84d28494-200a-4877-8e0e-6ad2739f82a3)

Instance Runner Fleet Dashboard:
![image](https://github.com/user-attachments/assets/baadbd19-69db-41d8-bdb6-8401caa31753)

Search Popup (commands text bottom right)
![image](https://github.com/user-attachments/assets/588b9b13-47fc-4f6d-aba9-4a64c0f3190d)

2024-12-27 10:56 UTC, Thomas-Philippot commented
Great, Thanks for the review
I will work on theses issues in the next days

2024-12-27 15:52 UTC, Thomas-Philippot commented
Unfortunately I might not have access to all these pages :
> Colors on Security Dashboard
> Compliance Center Status
> Header on Security View in Pipeline
> Repository > CI/CD Settings > Runner
> Repository > General Settings > Service Desk 
> Instance Runner View
> Instance Runner Fleet Dashboard

This is now done
> Search Popup :heavy_check_mark: 
> Readability on issue labels: :heavy_check_mark:

2024-12-27 17:28 UTC, uncenter commented on styles/gitlab/catppuccin.user.css
> +      }
Might be a good place to create a mixin or similar to avoid repeating the exact same lines only with different classnames and colors.

2024-12-30 11:46 UTC, Thomas-Philippot commented
Sorry for the mass review requests, I just wanted to update the branch

2024-12-30 11:56 UTC, comfysage commented
> Sorry for the mass review requests, I just wanted to update the branch

the review requests got triggered because you pushed changes to other userstyles. you probably accidentally added some formatting changes. you should be able to revert the commit and uncommit the changes.

2024-12-31 19:43 UTC, comfysage commented
do you want to convert this to a draft and work on it further?
you'll be able to convert it to a full pr and request a review when you feel it's ready <3

2025-01-02 12:36 UTC, uncenter commented
Going to mark this as a draft as mentioned to spare some notifications and more clearly signal the work that needs to be done :) thanks again for your continued work on this @Thomas-Philippot, excited for this to be added!

2025-01-05 20:48 UTC, thelooter commented
![image](https://github.com/user-attachments/assets/b52bc2e4-1e4a-48b4-8864-11aeb62058f6)
Merge Request approval widget has unreadable header

2025-01-06 22:10 UTC, Thomas-Philippot commented
Last change on graph page was impacting this section as well.

![image](https://github.com/user-attachments/assets/74a927eb-83aa-493e-9537-fd4283912c08)

Fixed :+1:

2025-04-30 16:49 UTC, uncenter commented on styles/gitlab/catppuccin.user.less
> +    --gl-banner-promo-border-color: @surface0;
I think a lot of these more specific component variables could be removed and we can fall back to the base color variables in most cases?

2025-04-30 16:51 UTC, uncenter commented
Pushed some fixes and improvements. The majority of the site is themed with variables (now?), making this a very efficient/small userstyle. Still some fine grained bits to iron out but I'd say we can open this up to some testing by userstyles maintainers/staff 👀

@Thomas-Philippot not sure how much interest you still have in this pull request - would love to continue to work on this alongside you, but no worries if you don't want to do any more :)

2025-04-30 17:46 UTC, Thomas-Philippot commented
That's very good news !

Haven't checked out the css variables nice the last commits but I'm still interested in getting this done ✅ 

I will look into this tomorrow as I'm on a day off

2025-05-01 11:48 UTC, Thomas-Philippot commented on styles/gitlab/catppuccin.user.less
> +    --gl-banner-promo-border-color: @surface0;
Yes ! looks like new variables was introduced, so these are no longer needed

2025-05-01 11:52 UTC, uncenter commented on styles/gitlab/catppuccin.user.less
> +    }
Why is this latte specific?

2025-05-01 11:56 UTC, Thomas-Philippot commented
The userstyle looks a lot cleaner !

I had to add a little tweak for the MR block because it has no background color on light mode
and I themed the diffs in code.

Didn't noticed any unreadable things, but as the website is huge I might miss some.
# MR section
## Default
![image](https://github.com/user-attachments/assets/95e7292e-13f3-400a-8743-6ffaf2150a81)

## Before
![image](https://github.com/user-attachments/assets/229cba8a-abd2-46a8-877c-2e7d6733da6f)


## After
![image](https://github.com/user-attachments/assets/fdc200fb-4124-48e5-8571-d1a9cfc76f40)

# Diffs

## Before
![image](https://github.com/user-attachments/assets/c5594996-3e44-4a03-8775-83f041c50a3e)

## After
![image](https://github.com/user-attachments/assets/72a569fa-708d-4bb4-b4a8-6ed914a26b02)

2025-05-01 12:32 UTC, uncenter commented on styles/gitlab/catppuccin.user.less
> +    --gl-banner-promo-border-color: @surface0;
I haven't deleted these quite yet, but I'll try it out and see how much breaks if anything.

2025-05-02 08:09 UTC, Thomas-Philippot commented on styles/gitlab/catppuccin.user.less
> +    }
That's for the MR section mentioned in latest comment. This section is darker than the default background only on dark mode. On light mode their is no "background"

## Default Dark mode

![image](https://github.com/user-attachments/assets/7f991460-5c5b-41a8-bb7e-89741933fa1f)

## Default Light mode

![image](https://github.com/user-attachments/assets/67169d74-be24-4765-885d-b0c7af864013)

As it uses a variable that itself uses the `--neutral-10` variable, I didn't wanted to style anything else by changing this variable value for the whole website.

2025-05-03 17:49 UTC, uncenter commented
I'm thinking instead of theming the generic `--gl-color` variables, we continue theming the more fine-grained/component-specific variable tokens. We can be more careful and specific to the style guide, it is more understandable when you need to fix something, etc. From what I have locally it adds about 200 lines but some of those include variables I haven't seen used yet that could just be removed. If you are okay with trying this route I could push what I have locally so you can see, we can always revert back.

2025-05-12 14:06 UTC, Thomas-Philippot commented
Maybe we could use both ways ?

I feel like with this approach, we have to look for every bit of buttons and text to see if it's themed or not.
Can't we theme globally and after that change the specifics that didn't fit ?

2025-06-26 16:14 UTC, Thomas-Philippot commented
just added a couple of classes to theme the code and pipeline pages.

I've been using this version for a couple days now and it's fine by me

2025-06-27 01:51 UTC, uncenter commented
> Maybe we could use both ways ?
> 
> I feel like with this approach, we have to look for every bit of buttons and text to see if it's themed or not. Can't we theme globally and after that change the specifics that didn't fit ?

Sorry I meant to respond to this a long time ago. I was finding it frustrating doing the initial route and so far this version is working a little better for me. If you find some areas we can simplify without breaking things that's great too.

2025-06-27 01:52 UTC, uncenter commented on styles/gitlab/catppuccin.user.less
> +    }
Is this still necessary?

2025-06-27 01:59 UTC, uncenter requested changes

2025-06-27 01:59 UTC, uncenter commented on styles/gitlab/catppuccin.user.less
> +    }
See lines 601-647. I'd like to use nesting much more than you have here, and this seems partially redundant. Please fold related styling like this into the aforementioned existing section on theming code blocks.

2025-06-27 01:59 UTC, uncenter commented on styles/gitlab/catppuccin.user.less
> +    }
This comment and these classes don't make it clear to me where these classes are used. Can you elaborate more in a comment here and we can brainstorm ways to document it better?

2025-06-27 01:59 UTC, uncenter commented on styles/gitlab/catppuccin.user.less
> +    }
These seem like the classnames of Pygments or Chroma, though I also see you included some highlight.js/hljs classes - they probably use a combination of the two/three for preview and live editing or something. See https://github.com/catppuccin/userstyles/blob/main/docs/guide/syntax-highlighting.md for how to import these classes instead of hard coding them here.

2025-06-27 01:59 UTC, uncenter commented on styles/gitlab/catppuccin.user.less
> +    }
Let's group these - I think pipeline/CI related styling? - into a block with a generic class that encompasses all of them (I'm assuming there is at least _something_ like that?)

2025-06-27 01:59 UTC, uncenter commented on styles/gitlab/catppuccin.user.less
> +    }
```suggestion
    .note-button.add-diff-note {
      background-color: @base;
      border-color: @accent;
      color: @accent;
      
      &:hover {
        background-color: @accent;
        color: @base;
      }
    }
```

2025-06-27 01:59 UTC, uncenter commented on styles/gitlab/catppuccin.user.less
> +    --gl-illustration-isometric-base-side-fill-color: #aea5d6;
Let me know if you know of any pages with illustrations/graphics. Hopefully these variables can actually help us theme those!

2025-06-27 01:59 UTC, uncenter commented on styles/gitlab/catppuccin.user.less
> +    --gl-action-danger-background-color-active: rgba(174, 24, 0, 0.24);
We should try to find where these are used or outright delete these non-palette color variables. A trick is you can set them all to `red` and it stands out in the UI a lot that way.

2025-12-31 20:18 UTC, ninetailedtori commented
This has been untouched in half a year from what I can see, am I allowed to hijack this PR? :3

2025-12-31 20:47 UTC, WalkQuackBack commented
> This has been untouched in half a year from what I can see, am I allowed to hijack this PR? :3

Typically, we do a close then reland process, like with DeepSeek. If you make a new PR, this can be closed with a superseded note.

2025-12-31 21:45 UTC, uncenter commented
> This has been untouched in half a year from what I can see, am I allowed to hijack this PR? :3

Please look at the conversation to understand why though. A large part is the decision between which approach for theming which set of variables.

2025-12-31 23:21 UTC, ninetailedtori commented
For official record on this ticket, personally, I think setting the semantic design tokens with any required contextual ones, would be best, as opposed to the constant design tokens of the colours, because our design style guidelines aren't just an LUT that map a colourspace, but a style on its own that actually maps the semantic tokens to colours, so our decisions on which colour tokens should be linked to wat would likely differ in several places. As such it would be cleanest to refer to the semantics and ignore the colour tokens :]

2026-07-12 06:10 UTC, WalkQuackBack commented
Close due to inactivity. If someone else would like to pick this up, they may create a new PR.

2026-07-12 06:10 UTC, closed without merging