feat(grabify): init
catppuccin/userstyles pull request #1404
Opened 2024-10-27 13:54 UTC by trinkey

## 🎉 Theme for Website 🎉
Grabify is a link shortener website that also collects basic information about everyone who clicks the link

## 💬 Additional Comments 💬
no

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/scripts/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - [x] `catppuccin.user.css` - all the CSS for the userstyle, based on the
        template.
  - [x] `preview.webp` - composite image of all four individual flavor screenshots (taken with the default accent color of mauve) stitched together, generated via [Catwalk](https://github.com/catppuccin/catwalk).

2024-10-27 22:45 UTC, comfysage approved these changes

2024-11-11 03:41 UTC, uncenter requested changes

2024-11-11 03:41 UTC, uncenter commented on styles/grabify/catppuccin.user.css
> +    }
```suggestion
    // Live support box
    #wrapper ~ div:has(iframe[style*="color-scheme:light"]) {
      display: none !important;
    }
```

2024-11-11 03:41 UTC, uncenter commented on styles/grabify/catppuccin.user.css
> +      }
```suggestion
      color: @accent-color !important;

      &:hover,
      &:focus {
        color: darken(@accent-color, 5%) !important;
      }
```

2024-11-11 05:49 UTC, uncenter approved these changes

2024-11-11 11:01 UTC, isabelroses approved these changes

2024-11-11 11:01 UTC, merged