feat(searxng): visited link colour + change default accent to blue
catppuccin/userstyles pull request #1450
Opened 2024-11-14 14:49 UTC by DokterKaj

## 🔧 What does this fix? 🔧

- Adds an option to customise the colour of visited links
- Changes the default accent to blue and the default visited colour to mauve because links are usually blue and visited links are usually purple

This PR would make this userstyle inconsistent with all the other Catppuccin userstyles since it uses blue instead of mauve as the default accent and also adds an additional variable (the visited links colour), so if that is undesirable, we can go the route of other Catppuccin browser userstyles by hard-coding links to be blue and visited links to be mauve.

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [x] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

2024-11-14 15:51 UTC, uncenter commented
The default accent is always the same across websites, we don't change it for specific userstyles.

2024-11-14 16:06 UTC, DokterKaj commented
In that case it's probably best to hard-code links as blue

Should visited links be hard-coded as mauve or be accented?

2024-11-14 16:15 UTC, uncenter commented
Well, according to the style guide visited/followed links would be lavender I believe, not mauve. We haven't made a complete decision on accent links vs style guide links yet, it is likely up to the maintainer to decide which they think looks better for a specific userstyle.

2024-11-14 17:11 UTC, DokterKaj commented
Lavender is not quite distinct enough from blue at a glance, so I think I'll still go with mauve like the Brave and DDG userstyles.

2024-11-14 17:13 UTC, DokterKaj commented
Not sure where `--color-result-detail-link` is used but it has "link" in the name so best to make it blue anyway

2024-11-14 17:35 UTC, sgoudham commented
Just my two cents, I don't think we should accept a contribution that is against the style guide. We're not making a tradeoff to improve some other highlight in this case either.

Also it does make this userstyles inconsistent with the others. As it stands, none of the userstyles support differentiation between links, on hover and visited so we'd probably just have to encourage users to make local changes if they want that at the minute.

In the future, we can probably look towards supporting this with official shades? Curious what @isabelroses and @uncenter think.

2024-11-16 16:05 UTC, DokterKaj commented
> Just my two cents, I don't think we should accept a contribution that is against the style guide.

Do the other browser userstyles have to have visited links be changed to lavender then?

> We're not making a tradeoff to improve some other highlight in this case either.

Not quite clear on what this means, sorry

2024-11-17 12:46 UTC, sgoudham commented
> Do the other browser userstyles have to have visited links be changed to lavender then?

I believe the style guide wasn't necessarily followed here since lavender itself is offered as an accent colour. I don't think it's feasible to update all the userstyles to that.

We'll probably have to define official shades of colours as part of the style guide so that userstyles can standardise on the amount to lighten/darken the links for hover/visited.

> Not quite clear on what this means, sorry

Sorry ignore me there, what I said wasn't really relevant.

2024-11-19 01:12 UTC, DokterKaj commented
> I believe the style guide wasn't necessarily followed here since lavender itself is offered as an accent colour.

This shouldn't be a problem since this PR would make links no longer accented; they'd just be blue and mauve (or blue and lavender, if we must adhere to the style guide) so there shouldn't be any clashing.

> We'll probably have to define official shades of colours as part of the style guide so that userstyles can standardise on the amount to lighten/darken the links for hover/visited.

That would be ideal, but for now this is probably the best way to re-add this functionality of distinguishing visited links.

2026-01-06 17:32 UTC, uncenter requested changes
Sorry for the delay on this. Updated with main, and I think we should be using lavender instead of mauve for visited links - this matches the "followed links" of the style guide. I will update this in the Google userstyle as well.

2026-01-06 17:32 UTC, uncenter commented on styles/searxng/catppuccin.user.less
> +    --color-url-visited-font: @mauve;
```suggestion
    --color-url-visited-font: @lavender;
```

2026-01-06 17:32 UTC, uncenter commented on styles/searxng/catppuccin.user.less
> +    --color-result-link-visited-font: @mauve;
```suggestion
    --color-result-link-visited-font: @lavender;
```

2026-01-06 17:33 UTC, uncenter approved these changes

2026-01-07 09:01 UTC, ryanccn reviewed
Personally, I disagree with the idea of changing links to the standard style guide link color. IMO in the case of search engines links *are* the primary interactive elements of the user interface and therefore should follow the accent color rather than the usual prose link color. (Otherwise I don't think there would be a whole lot of opportunities to see the configured accent color other than the tab bar.)

2026-01-07 21:48 UTC, uncenter commented
> Personally, I disagree with the idea of changing links to the standard style guide link color. IMO in the case of search engines links _are_ the primary interactive elements of the user interface and therefore should follow the accent color rather than the usual prose link color. (Otherwise I don't think there would be a whole lot of opportunities to see the configured accent color other than the tab bar.)

I can agree but then we'll need to document this - specifically define "the primary interactive elements" of an interface and outline the exception to style guide practices. cc @WalkQuackBack

2026-01-07 22:43 UTC, uncenter commented
@ryanccn how do you propose we style visited links differently from normal links for a search engine userstyle, assuming the base link is accent? We usually use (recently at least) `lighten(@accent, 5%)` for links on hover, fwiw.

2026-01-07 22:47 UTC, uncenter commented
> Lavender is not quite distinct enough from blue at a glance, so I think I'll still go with mauve like the Brave and DDG userstyles.

It's also worth noting this complaint. Not sure if @DokterKaj is still active anymore, but if anyone feels the same they should file an issue on catppuccin/catppuccin and get the style guide changed.

2026-07-12 06:13 UTC, WalkQuackBack commented
I'm really sorry for getting to this so late, but I think this is okay to merge for now in parity with the other search engine ports.

2026-07-12 06:13 UTC, WalkQuackBack approved these changes

2026-07-12 06:14 UTC, merged