feat(seventv): init
catppuccin/userstyles pull request #1491
Opened 2024-12-14 13:51 UTC by mxgic1337

## 🎉 Theme for [7TV](https://7tv.app) 🎉

7TV is a platform and a browser extension that provides custom emotes for Twitch.
![Preview](https://github.com/user-attachments/assets/4e2b2b43-3b0e-49c6-a396-7dfe4d5aad89)

## 💬 Additional Comments 💬

This userstyle only themes the 7tv.app website. The extension is unthemed.

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/scripts/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - [x] `catppuccin.user.css` - all the CSS for the userstyle, based on the
        template.
  - [x] `preview.webp` - composite image of all four individual flavor screenshots (taken with the default accent color of mauve) stitched together, generated via [Catwalk](https://github.com/catppuccin/catwalk).

2024-12-21 14:28 UTC, isabelroses commented on styles/seventv/catppuccin.user.css
> +    & {
If we are just using `&` we can remove it
```suggestion
```

2024-12-30 10:08 UTC, isabelroses requested changes
LGTM overall, 1 small issue with the gradients
![Uploading image.png…]()

2024-12-30 13:44 UTC, mxgic1337 commented
@isabelroses What is the issue? Also, should I rename the file to `catppuccin.user.less`?

2024-12-30 13:54 UTC, isabelroses commented
Oh the image didn't upload...
![image](https://github.com/user-attachments/assets/a48eccfc-bfc3-4c91-9594-4386e05ba7af)

>  Also, should I rename the file to catppuccin.user.less?

Yes, you can also remove the `vim` line at the bottom of the file.

2024-12-30 14:10 UTC, mxgic1337 commented
I'm not sure how I should style these gradients.

2024-12-30 14:16 UTC, isabelroses commented
> I'm not sure how I should style these gradients.

Thats pretty fair. I don't mind removing them since there is a few. Alternatively, you could reduce them a little. Like I choose herre

```less
radial-gradient(150% 180% at 50% 180%, #fab387, #f9e2af 1%, #cba6f7 25%, #181825 75%), var(--secondary) !important
```

cc: @uncenter

2024-12-31 08:39 UTC, isabelroses approved these changes

2024-12-31 19:30 UTC, merged

2024-12-31 19:40 UTC, uncenter commented
This was not approved by both staff members, as is required. Only staff should be merging init pull requests.

2024-12-31 19:42 UTC, uncenter commented
I'm going to leave review comments on this pull request hopefully later today that will need to be addressed in a follow up PR.

2024-12-31 20:07 UTC, mxgic1337 commented
> This was not approved by both staff members, as is required. Only staff should be merging init pull requests.

Oops, I thought that only one approval is required, sorry!

2024-12-31 20:09 UTC, uncenter commented
No worries, we need to work on our documentation and maintainer flow! It's definitely not clear at the moment. See the new "Custom GitHub bot" section on https://github.com/catppuccin/userstyles/issues/1357 for what it might look like in the future :)

2024-12-31 23:00 UTC, uncenter commented
> I'm going to leave review comments on this pull request hopefully later today that will need to be addressed in a follow up PR.

Looks really good! No changes from me, thanks for your work on this!