Planet Minecraft
catppuccin/userstyles pull request #200
Opened 2023-09-14 23:05 UTC by night-lake

## 🎉 Theme for [Planet Minecraft](https://planetminecraft.com)🎉

Planet Minecraft is a non-official website for Minecraft players to share, download and interact with resources such as skins, mods, resource packs, etc.

## 💬 Additional Comments 💬

> **Note**
> This theme is still in progress, if you have any comments or find something unthemed, please tell me in this PR! Thus, the catwalk will be generated when the theme is ready for merging.

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/src/userstyles.yml)
      file with information about the new userstyle.
- [ ] I have included the following files:
  - `catppuccin.user.css` - all the CSS for the userstyle, based on the
    template.
  - `assets/mocha.webp`, `assets/macchiato.webp`, `assets/frappe.webp` and
    `assets/latte.webp` - individual screenshots of the themed website, in all 4
    Catppuccin flavors.
  - `catwalk.webp` - image of all individual screenshots stitched together,
    generated via [catwalk](https://github.com/catppuccin/toolbox#-catwalk).

2023-09-14 23:40 UTC, night-lake commented
Known Issues:
- [ ] These icons aren't properly visible in Latte (should be Text)
	- ![image](https://github.com/catppuccin/userstyles/assets/32780515/c2d66a1e-7e7a-4918-a7a9-ae606c649bfa)
- [ ] The account dropdown isn't properly themed
	- ![image](https://github.com/catppuccin/userstyles/assets/32780515/bc9ccc38-4d4e-4c42-960d-27ef4ed2e5de)
- [ ] The Time Machine menu isn't properly themed, as well as basically the entire thing
	- ![image](https://github.com/catppuccin/userstyles/assets/32780515/337b972a-904e-41a0-a9d4-93c5521b0342)

2023-09-15 08:14 UTC, isabelroses requested changes
Some things still are not themed such as 
![image](https://github.com/catppuccin/userstyles/assets/71222764/a980c1d1-38bb-4282-ab79-008dd6cd61ac)
which is themed using the variable `--graphic-bg`.
as well as some button. 
![image](https://github.com/catppuccin/userstyles/assets/71222764/da38b364-977b-45ef-ad9a-b77c9ed7964d)

Perhaps checkout the root variables on the page as I have found a number of unthemed variables, perhaps they are not need ones but it could be done to prevent future issues.

2023-09-15 08:14 UTC, isabelroses commented on template/catppuccin.user.css
can you revert the changes you made to this file please.

2023-09-15 08:14 UTC, isabelroses commented on styles/planet-minecraft/catppuccin.user.css
> + *  @@accent – which is the desired Accent Color */
You don't need to keep all these comments in.

2023-09-15 11:56 UTC, night-lake commented
just for confirmation, im coloring the panes in the correct order right (mantle for lowest, base for highest)

2023-09-15 12:03 UTC, isabelroses commented
> just for confirmation, im coloring the panes in the correct order right (mantle for lowest, base for highest)

When working inwards try make the colors become lighter going from crust to mantle to base, but keep base where the main focus is. Perhaps where any cards are you could use something like surface0 etc.

2023-09-15 20:44 UTC, night-lake commented
i still have to fix these buttons
![image](https://github.com/catppuccin/userstyles/assets/32780515/603cb961-4f5c-49f0-a462-9770cfc1197e)

2023-09-17 10:16 UTC, isabelroses commented
Just some things to point out.
1. The text chat has unthemed borders: 
![image](https://github.com/catppuccin/userstyles/assets/71222764/17c495c4-1338-4ff4-a403-82858490d1f6)
2. group notifications are only partly themed
![image](https://github.com/catppuccin/userstyles/assets/71222764/00e5dd8e-af26-4920-9280-bbe98c0f79f9)
3. Buttons upon a hover lose there darker text.

2023-09-30 22:38 UTC, isabelroses approved these changes

2023-09-30 22:39 UTC, merged