Add Spotify Web userstyle
catppuccin/userstyles pull request #329
Opened 2023-11-18 03:45 UTC by Tnixc

## 🎉 Theme for Spotify Web 🎉

A theme for the web version of spotify!

## 💬 Additional Comments 💬

There are some svgs that I couldn't figure out how to theme.

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/src/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - `catppuccin.user.css` - all the CSS for the userstyle, based on the
    template.
  - `assets/mocha.webp`, `assets/macchiato.webp`, `assets/frappe.webp` and
    `assets/latte.webp` - individual screenshots of the themed website, in all 4
    Catppuccin flavors.
  - `catwalk.webp` - image of all individual screenshots stitched together,
    generated via [catwalk](https://github.com/catppuccin/toolbox#-catwalk).

2023-11-18 04:07 UTC, uncenter commented on styles/spotify-web/catppuccin.user.css
> +@-moz-document regexp('https://open\.spotify\.com/.*')
You could probably just do a `@-moz-document domain('open.spotify.com*')`.

2023-11-18 04:09 UTC, uncenter commented on styles/spotify-web/catppuccin.user.css
> +} /* /@-moz-document */
You can remove this `/* /@-moz-document */` comment at the end, it was a mistake in the template I think.

2023-11-18 04:12 UTC, uncenter commented on styles/spotify-web/catppuccin.user.css
> +@-moz-document domain('open.spotify.com*')
Sorry make sure to remove the star at the end there.

2023-11-18 04:23 UTC, uncenter commented on styles/spotify-web/catppuccin.user.css
> +    }
```suggestion
    .kmZeYl {
      background-color: @mantle;
      &:hover {
        background-color: @crust;
      }
    }
```

2023-11-18 04:34 UTC, uncenter requested changes

2023-11-18 04:34 UTC, uncenter commented on styles/spotify-web/catppuccin.user.css
> +@name spotify-web Catppuccin
```suggestion
@name Spotify Web Catppuccin
```

2023-11-18 04:34 UTC, uncenter commented on styles/spotify-web/catppuccin.user.css
> +@description Soothing pastel theme for spotify-web
```suggestion
@description Soothing pastel theme for Spotify Web
```

2023-11-18 04:36 UTC, uncenter commented
Sorry I probably should have done that in one suggestion :D

2023-11-18 08:50 UTC, nekowinston requested changes
The screenshots are currently not stored with LFS, so I couldn't resolve the latest merge from main for you.

2023-11-18 18:26 UTC, isabelroses commented on styles/spotify-web/catppuccin.user.css
> +      --background-unsafe-for-small-text-press: @base;
Can you look over these duplicated properties

2023-11-18 18:36 UTC, isabelroses requested changes
<details>
<summary>
Hover items in general seem to be broken.
</summary>

![image](https://github.com/catppuccin/userstyles/assets/71222764/56dbf74a-3fb3-46f3-b4ce-db48c1412ec5)
![image](https://github.com/catppuccin/userstyles/assets/71222764/507318d7-34e6-4d15-88b2-ced5d457b4f9)
![image](https://github.com/catppuccin/userstyles/assets/71222764/057794cc-5962-4dce-850f-9100eeb2e42b)
![image](https://github.com/catppuccin/userstyles/assets/71222764/eb5bfde2-6c05-46af-861d-f1f43bf81841)
![image](https://github.com/catppuccin/userstyles/assets/71222764/dcd6255a-3111-4f97-911f-313bd156af92)

</details>
<details>
<summary>
This popup seems too be the wrong colour
</summary>

![image](https://github.com/catppuccin/userstyles/assets/71222764/15fccd5b-fa46-4da1-84d5-c60c99479694)

</details>
<details>
<summary>
The search library button seems to be broken
</summary>

![image](https://github.com/catppuccin/userstyles/assets/71222764/13c73456-c567-4ed9-9775-9d8d1a190bbc)

</details>

2023-11-18 18:40 UTC, nekowinston approved these changes

2023-11-18 19:16 UTC, isabelroses commented on styles/spotify-web/catppuccin.user.css
> +}
```suggestion
}
// vim:ft=less
```

2023-11-19 17:39 UTC, isabelroses approved these changes

2023-11-19 17:39 UTC, merged