fix: Instagram Share box colors
catppuccin/userstyles pull request #366
Opened 2023-12-02 22:07 UTC by GenShibe

## 🔧 What does this fix? 🔧
The share box when sharing a post/reel.
this took way too long and i am now annoyed at instagram. Thanks lizard man for not making it easy

2023-12-02 22:41 UTC, isabelroses requested changes
Please update the version number

2023-12-02 22:44 UTC, GenShibe commented
i keep forgetting to 💀

2023-12-02 22:49 UTC, isabelroses approved these changes

2023-12-09 18:05 UTC, isabelroses approved these changes

2023-12-09 18:06 UTC, merged