feat(wikipedia): init
catppuccin/userstyles pull request #446
Opened 2024-01-18 02:24 UTC by GitMuslim

## 🎉 Theme for Wikipedia  🎉

Wikipedia

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/src/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - `catppuccin.user.css` - all the CSS for the userstyle, based on the
    template.
  - `assets/mocha.webp`, `assets/macchiato.webp`, `assets/frappe.webp` and
    `assets/latte.webp` - individual screenshots of the themed website, in all 4
    Catppuccin flavors.
  - `catwalk.webp` - image of all individual screenshots stitched together,
    generated via [catwalk](https://github.com/catppuccin/toolbox#-catwalk).

2024-01-18 02:31 UTC, isabelroses commented
![image](https://github.com/catppuccin/userstyles/assets/71222764/e4d1a64f-6046-4837-a8f6-b14fb86fe0cb)

this create account page is improperly themed

2024-01-18 02:52 UTC, uncenter commented
**Homepage language selector**:
![Screenshot 2024-01-17 at 21 44 59 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/73f71e84-dcf2-46e4-8449-d5f2c8de235f)

**Overscroll areas above and below page**:
![Screenshot 2024-01-17 at 21 46 35 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/af8bbfe1-1f8b-45d8-88aa-8a0e5d42865e)

**Peek boxes settings icon**:
![Screenshot 2024-01-17 at 21 48 03 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/2c382b64-6f1d-49e7-9696-16407b345979)

**Picture of the day page**:
https://en.wikipedia.org/wiki/Template:POTD/2024-01-17

**Search icon** (MEDIUM/SMALL VIEWPORT WIDTH ONLY):
![Screenshot 2024-01-17 at 21 49 30 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/579a962d-c602-4a19-bdde-97fbe1b91913)

**TOC button** (MEDIUM/SMALL VIEWPORT WIDTH ONLY):
(see top left white box)
![Screenshot 2024-01-17 at 21 50 40 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/96e8ee0b-fdb9-4bdd-a9cc-7603847ed30f)

**Note/callout boxes**:
(https://en.wikipedia.org/wiki/Wikipedia:Citation_needed)
![Screenshot 2024-01-17 at 21 51 39 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/bdf6d338-399a-4732-8a4d-45202a08b89d)

2024-01-18 23:14 UTC, uncenter commented on styles/wikipedia/catppuccin.user.css
> +      border-top: 1px solid @surface0;
```suggestion
      border-bottom-color: @surface2;
    }
    
    .mw-footer {
      border-top-color: @surface2;
    }
    
    .bookshelf {
      border-top-color: @surface0;
```

2024-01-18 23:14 UTC, uncenter commented on styles/wikipedia/catppuccin.user.css
> +      border-top: 2px solid @surface0;
```suggestion
      border-top-color: @surface0;
```

2024-01-18 23:15 UTC, uncenter commented on styles/wikipedia/catppuccin.user.css
> +      border-bottom: 1px solid @surface2;
```suggestion
      border-bottom-color: @surface0;
    }
    
    hr {
      border-bottom-color: @surface2;
```

2024-01-18 23:15 UTC, uncenter commented on styles/wikipedia/catppuccin.user.css
> +        border-right: 1px solid @surface2;
```suggestion
      border-top-color: @surface2;
      border-left-color:@surface2;
      border-right-color: @surface2;
      & > figcaption {
        background-color: @mantle !important;
        color: @text !important;
        border-bottom-color: @surface2;
        border-left-color: @surface2;
        border-right-color: @surface2;
```

2024-01-18 23:16 UTC, uncenter commented on styles/wikipedia/catppuccin.user.css
> +      border-left: 1px solid @surface2;
```suggestion
      border-left-color: @surface2;
```

2024-01-23 11:39 UTC, isabelroses commented
Some tables have bad contrast:
![image](https://github.com/catppuccin/userstyles/assets/71222764/c81658d8-b327-401a-b179-ab1d02f9d246)

When performing a search the background appears white:
![image](https://github.com/catppuccin/userstyles/assets/71222764/81745e76-73f8-4210-9829-1b6b2a53a45e)

When looking around i could only find these pages (given they are not visited that much):
- https://en.wikipedia.org/wiki/Talk:Main_Page
- https://en.wikipedia.org/w/index.php?title=Main_Page&action=history
- https://en.wikipedia.org/w/index.php?title=Main_Page&action=edit
- https://en.wikipedia.org/wiki/Talk:Main_Page#Main_Page_error_reports

one example of what the pages might look like:
![image](https://github.com/catppuccin/userstyles/assets/71222764/f5fad1a9-3a68-4376-b28f-4ff4561dbeda)

Other then that, I cannot find anything to breaking.

2024-01-28 17:01 UTC, isabelroses requested changes
see prior comments

2024-02-06 22:48 UTC, GenShibe commented
![image](https://github.com/catppuccin/userstyles/assets/29279972/03a35649-8468-4ac9-90ad-bc17ee1ac5a3)
![image](https://github.com/catppuccin/userstyles/assets/29279972/0033b6d8-9e0a-4267-8f0f-e05fbff92503)
![image](https://github.com/catppuccin/userstyles/assets/29279972/fe5fe7a6-8b92-493a-a90b-5198062489ee)
a bunch of table stuff needs to be themed

2024-02-08 07:06 UTC, GitMuslim commented
@isabelroses @GenShibe fixed all of the above

2024-02-08 08:07 UTC, isabelroses requested changes
The last blocker I can realisitcly see is the contrast here
![image](https://github.com/catppuccin/userstyles/assets/71222764/31155a5a-2a35-48d3-949b-f713f19c0201)
[link to reproduce](https://en.wikipedia.org/wiki/Second_War_of_Scottish_Independence)

2024-02-08 09:25 UTC, GitMuslim commented
done

2024-02-08 10:01 UTC, merged