Feat(archwiki): init
catppuccin/userstyles pull request #479
Opened 2024-01-29 02:58 UTC by GenShibe

## 🎉 Theme for [Arch WIki](https://wiki.archlinux.org/) 🎉
Arch wiki is the wiki page for all things arch/arch related

## 💬 Additional Comments 💬
This is only a draft, as i cannot figure out how to theme dark mode because no css variables were changed

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/src/userstyles.yml)
      file with information about the new userstyle.
- [ ] I have included the following files:
  - `catppuccin.user.css` - all the CSS for the userstyle, based on the
    template.
  - `assets/mocha.webp`, `assets/macchiato.webp`, `assets/frappe.webp` and
    `assets/latte.webp` - individual screenshots of the themed website, in all 4
    Catppuccin flavors.
  - `catwalk.webp` - image of all individual screenshots stitched together,
    generated via [catwalk](https://github.com/catppuccin/toolbox#-catwalk).

2024-01-29 03:42 UTC, uncenter commented on styles/archwiki/Catppuccin.user.css
> +          border-bottom: 5px @blue solid !important;
```suggestion
          border-bottom-color: @blue;
```

2024-01-29 03:43 UTC, uncenter commented on styles/archwiki/Catppuccin.user.css
> +          border-bottom: 5px @blue solid
```suggestion
          border-bottom-color: @blue;
```

2024-01-29 23:35 UTC, uncenter commented on scripts/userstyles.yml
> +      current-maintainers: [*genshibe]
```suggestion
    name: Arch Wiki
    category: productivity
    readme:
    app-link: "https://wiki.archlinux.org/"
      usage: "Make sure to use the default **Light** theme"
    current-maintainers: [*genshibe]
```

2024-01-29 23:39 UTC, uncenter commented on scripts/userstyles.yml
> +    app-link: "https://wiki.archlinux.org/"
```suggestion
      app-link: "https://wiki.archlinux.org/"
```

2024-01-29 23:42 UTC, uncenter commented on scripts/userstyles.yml
> +    current-maintainers: [*genshibe]
```suggestion
      current-maintainers: [*genshibe]
```

2024-01-30 10:55 UTC, isabelroses requested changes

2024-01-30 10:55 UTC, isabelroses commented on styles/arch-wiki/Catppuccin.user.css
can you remove this file

2024-01-30 10:55 UTC, isabelroses commented on catwalk.webp
can you remove this file

2024-01-30 19:31 UTC, isabelroses approved these changes

2024-01-30 19:48 UTC, merged