Feat/duckduckgo
catppuccin/userstyles pull request #486
Opened 2024-01-31 06:01 UTC by GenShibe

## 🎉 Theme for [Duck Duck Go](https://duckduckgo.com) 🎉

## 💬 Additional Comments 💬
It's a search engine.

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/src/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - `catppuccin.user.css` - all the CSS for the userstyle, based on the
    template.
  - `assets/mocha.webp`, `assets/macchiato.webp`, `assets/frappe.webp` and
    `assets/latte.webp` - individual screenshots of the themed website, in all 4
    Catppuccin flavors.
  - `catwalk.webp` - image of all individual screenshots stitched together,
    generated via [catwalk](https://github.com/catppuccin/toolbox#-catwalk).

2024-01-31 18:32 UTC, sgoudham reviewed
Just leaving this here, we should hold off on merging this until I/we figure out how to display this style in the README of `catppuccin/catppuccin`

Essentially, it'll end up looking a bit dumb right now if 2 `DuckDuckGo`'s appear on the README so we might need to modify how its represented over there or maybe not merge it here (which I just learned is similar to `catppuccin/youtubemusic`)

2024-02-01 11:47 UTC, andreasgrafen commented
The bold statement would be that both DDG and youtubemusic are just packaged website that imitate native apps. Hence: Move everything into the userstyles repo. But then it could be argued that something like VS Code also is just a website when it comes down to it.

Anyhow; a little out of scope, but for youtubemusic it's basically the same stylesheet, no?  At that point I'd actually argue that it may be better to host is as a userstyle with bonud instructions as to how you can inject it into the packaged thing. But most people I know that use youtube music are using it in the browser anyway.
The same argument could be made about DDG as well.

Alternatively it could just be tagged accordingly like
- DuckDuckGo (Web)
- DuckDuckGo (Native)

2024-02-01 12:44 UTC, sgoudham commented
But the larger question is can we avoid having 2 "listings" of the same application :thinking:

2024-02-01 13:49 UTC, andreasgrafen commented
> But the larger question is can we avoid having 2 "listings" of the same application 🤔

By just having them as userstyles first and foremost – and if there are possibilities to inject them into a packaged desktop app, just put them as extra instructions. And we could still indicate that with an emoji key or something for the items where that's the case.

Would it be smart to move this discussion elsewhere since it's not really about the PR? xd

2024-02-02 00:53 UTC, uncenter requested changes

2024-02-02 00:53 UTC, uncenter commented on styles/duckduckgo/catppuccin.user.css
> +@-moz-document domain(duckduckgo.com) {
```suggestion
@-moz-document domain('duckduckgo.com') {
```

2024-02-02 00:53 UTC, uncenter commented on styles/duckduckgo/catppuccin.user.css
> +        }
```suggestion
```

2024-02-02 00:53 UTC, uncenter commented on styles/duckduckgo/catppuccin.user.css
> +  */
```suggestion
    @media (prefers-color-scheme: light) {
        :root {
            #catppuccin(@lightFlavor, @accentColor);
        }
    }
    @media (prefers-color-scheme: dark) {
        :root {
            #catppuccin(@darkFlavor, @accentColor);
        }
    }
```

2024-02-14 22:17 UTC, night-lake submitted a review, later dismissed
Alright so just a few issues I noticed:
- The search button on the main page and search result titles default to blue accent and do not respect the set accent
- This. Just this. No comment.
![Why is it in a box?](https://github.com/catppuccin/userstyles/assets/32780515/302c4ba4-1a4f-4279-a568-393928139a1b)
- Filters aren't themed either
- Some unthemed text
	- ![image](https://github.com/catppuccin/userstyles/assets/32780515/1ef0e4f6-a97e-49c3-9692-24ab1cc2f4f8)
	- ![image](https://github.com/catppuccin/userstyles/assets/32780515/02985c26-1d25-41ad-8211-d4de8b56eec0)



(I am able to fix these, just making a list so it's known what needs to be looked at :P)

2024-02-15 07:47 UTC, GenShibe commented
> Alright so just a few issues I noticed:
> 
> * The search button on the main page and search result titles default to blue accent and do not respect the set accent
> * This. Just this. No comment.
>   ![Why is it in a box?](https://private-user-images.githubusercontent.com/32780515/304891378-302c4ba4-1a4f-4279-a568-393928139a1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5ODM0NzMsIm5iZiI6MTcwNzk4MzE3MywicGF0aCI6Ii8zMjc4MDUxNS8zMDQ4OTEzNzgtMzAyYzRiYTQtMWE0Zi00Mjc5LWE1NjgtMzkzOTI4MTM5YTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA3NDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViOGVkMzNhZWNiMDI5Y2NlOTRhYzBmOWE5M2I0NTEzZjM2NmU2NzcwOGQ2Mzk0MGQ5ZjU0NDc3NGZkYjRmYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0N91SQ1zhx5HW9zw4H5UjNHj4zm_3KP5UDeE1A9EMJw)
> * Filters aren't themed either
> * Some unthemed text
>   
>   * ![image](https://private-user-images.githubusercontent.com/32780515/304892533-1ef0e4f6-a97e-49c3-9692-24ab1cc2f4f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5ODM0NzMsIm5iZiI6MTcwNzk4MzE3MywicGF0aCI6Ii8zMjc4MDUxNS8zMDQ4OTI1MzMtMWVmMGU0ZjYtYTk3ZS00OWMzLTk2OTItMjRhYjFjYzJmNGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA3NDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZThjNzQ2ZDgyYTY2MTQwZTNkZjk4NGQxOGVmZGZjZDhlMDBhMWYyMjkyM2Q2NjU4Yzk1MzBiM2NjOGJiZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u7J_13BXc6ZATRrCZsJB2FoVgAs6Cy-mFC_2G4Y8f9s)
>   * ![image](https://private-user-images.githubusercontent.com/32780515/304892752-02985c26-1d25-41ad-8211-d4de8b56eec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5ODM0NzMsIm5iZiI6MTcwNzk4MzE3MywicGF0aCI6Ii8zMjc4MDUxNS8zMDQ4OTI3NTItMDI5ODVjMjYtMWQyNS00MWFkLTgyMTEtZDRkZThiNTZlZWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA3NDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMGQyZGU3NWViYzliMzFhMjhkZTI3MGM0MjFlOGM0NjIwZmVkMGJlNjBjODdmNTk5MWVkYmIxM2Q3ZThlNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dqrGE7G0TuiKa7N-e8VRdTZVZ6jwsfJvQV9P3AjJZ5U)
> 
> (I am able to fix these, just making a list so it's known what needs to be looked at :P)

if you want to fix them, go right ahead, not going to stop you lol, i'll get to them probably tmr or friday

2024-02-15 08:15 UTC, GenShibe commented
> * The search button on the main page and search result titles default to blue accent and do not respect the set accent


regarding the links, i discussed this with the userstyle queen herself, bell, and she said that following google and having blue links was ok so i'm leaving that part as is

2024-02-15 21:08 UTC, nekowinston commented
> Just leaving this here, we should hold off on merging this until I/we figure out how to display this style in the README of `catppuccin/catppuccin`
> 
> Essentially, it'll end up looking a bit dumb right now if 2 `DuckDuckGo`'s appear on the README so we might need to modify how its represented over there or maybe not merge it here (which I just learned is similar to `catppuccin/youtubemusic`)

Just saw this comment, I thought the intention was to archive DuckDuckGo, and I commented as much on an issue over there yesterday. I'd be fine with doing that and taking ctp/duckduckgo off the port index.

2024-02-16 19:58 UTC, night-lake commented
> > * The search button on the main page and search result titles default to blue accent and do not respect the set accent
> 
> regarding the links, i discussed this with the userstyle queen herself, bell, and she said that following google and having blue links was ok so i'm leaving that part as is

I feel like it should be an option on whether to use blue or the accent, unless that is bell territory.

2024-02-16 20:04 UTC, GenShibe commented
> > > * The search button on the main page and search result titles default to blue accent and do not respect the set accent
> 
> > 
> 
> > regarding the links, i discussed this with the userstyle queen herself, bell, and she said that following google and having blue links was ok so i'm leaving that part as is
> 
> 
> 
> I feel like it should be an option on whether to use blue or the accent, unless that is bell territory.

@isabelroses ahem, belllllll

2024-02-16 20:18 UTC, isabelroses commented
> I feel like it should be an option on whether to use blue or the accent, unless that is bell territory.

Following catppuccin's color guidelines we should be using blue for links.

2024-02-17 13:26 UTC, sgoudham commented
Is this ready to be merged in btw? @GenShibe @isabelroses 

If it is, then we can merge it in and archive the existing catppuccin/duckduckgo repository as winston previously mentioned.

2024-02-17 13:39 UTC, isabelroses commented
> Is this ready to be merged in btw? @GenShibe @isabelroses
> 
> If it is, then we can merge it in and archive the existing catppuccin/duckduckgo repository as winston previously mentioned.

I think its good to merge unless gen wants to work on anything else.

2024-02-17 19:38 UTC, GenShibe commented
> > Is this ready to be merged in btw? @GenShibe @isabelroses
> > If it is, then we can merge it in and archive the existing catppuccin/duckduckgo repository as winston previously mentioned.
> 
> I think its good to merge unless gen wants to work on anything else.

pretty sure i've tackled the major stuff so it should be fine

2024-02-17 19:51 UTC, isabelroses approved these changes

2024-02-17 20:03 UTC, merged