feat(nextjs): init
catppuccin/userstyles pull request #495
Opened 2024-02-03 20:22 UTC by Dandraghas

## 🎉 Theme for [Next.js](https://nextjs.org) 🎉

The React Framework for the Web

## 💬 Additional Comments 💬

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/src/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - `catppuccin.user.css` - all the CSS for the userstyle, based on the
    template.
  - `assets/mocha.webp`, `assets/macchiato.webp`, `assets/frappe.webp` and
    `assets/latte.webp` - individual screenshots of the themed website, in all 4
    Catppuccin flavors.
  - `catwalk.webp` - image of all individual screenshots stitched together,
    generated via [catwalk](https://github.com/catppuccin/toolbox#-catwalk).

2024-02-03 20:29 UTC, uncenter requested changes

2024-02-03 20:29 UTC, uncenter commented on scripts/userstyles.yml
> +      current-maintainers: [ *Dandraghas ]
```suggestion
      current-maintainers: [*Dandraghas]
```

2024-02-03 20:37 UTC, isabelroses reviewed
Currently, links and other small things aren't themed see https://nextjs.org/docs for a set of examples.

2024-02-03 20:40 UTC, uncenter commented
You did the gray colors but not the rest of them (i.e. blue for links as @isabelroses said):
```css
.dark-theme, .invert-theme, :host, :root {
	--ds-gray-100: hsla(var(--ds-gray-100-value),1);
	--ds-gray-200: hsla(var(--ds-gray-200-value),1);
	--ds-gray-300: hsla(var(--ds-gray-300-value),1);
	--ds-gray-400: hsla(var(--ds-gray-400-value),1);
	--ds-gray-500: hsla(var(--ds-gray-500-value),1);
	--ds-gray-600: hsla(var(--ds-gray-600-value),1);
	--ds-gray-700: hsla(var(--ds-gray-700-value),1);
	--ds-gray-800: hsla(var(--ds-gray-800-value),1);
	--ds-gray-900: hsla(var(--ds-gray-900-value),1);
	--ds-gray-1000: hsla(var(--ds-gray-1000-value),1);
	--ds-blue-100: hsla(var(--ds-blue-100-value),1);
	--ds-blue-200: hsla(var(--ds-blue-200-value),1);
	--ds-blue-300: hsla(var(--ds-blue-300-value),1);
	--ds-blue-400: hsla(var(--ds-blue-400-value),1);
	--ds-blue-500: hsla(var(--ds-blue-500-value),1);
	--ds-blue-600: hsla(var(--ds-blue-600-value),1);
	--ds-blue-700: hsla(var(--ds-blue-700-value),1);
	--ds-blue-800: hsla(var(--ds-blue-800-value),1);
	--ds-blue-900: hsla(var(--ds-blue-900-value),1);
	--ds-blue-1000: hsla(var(--ds-blue-1000-value),1);
	--ds-amber-100: hsla(var(--ds-amber-100-value),1);
	--ds-amber-200: hsla(var(--ds-amber-200-value),1);
	--ds-amber-300: hsla(var(--ds-amber-300-value),1);
	--ds-amber-400: hsla(var(--ds-amber-400-value),1);
	--ds-amber-500: hsla(var(--ds-amber-500-value),1);
	--ds-amber-600: hsla(var(--ds-amber-600-value),1);
	--ds-amber-700: hsla(var(--ds-amber-700-value),1);
	--ds-amber-800: hsla(var(--ds-amber-800-value),1);
	--ds-amber-900: hsla(var(--ds-amber-900-value),1);
	--ds-amber-1000: hsla(var(--ds-amber-1000-value),1);
	--ds-red-100: hsla(var(--ds-red-100-value),1);
	--ds-red-200: hsla(var(--ds-red-200-value),1);
	--ds-red-300: hsla(var(--ds-red-300-value),1);
	--ds-red-400: hsla(var(--ds-red-400-value),1);
	--ds-red-500: hsla(var(--ds-red-500-value),1);
	--ds-red-600: hsla(var(--ds-red-600-value),1);
	--ds-red-700: hsla(var(--ds-red-700-value),1);
	--ds-red-800: hsla(var(--ds-red-800-value),1);
	--ds-red-900: hsla(var(--ds-red-900-value),1);
	--ds-red-1000: hsla(var(--ds-red-1000-value),1);
	--ds-green-100: hsla(var(--ds-green-100-value),1);
	--ds-green-200: hsla(var(--ds-green-200-value),1);
	--ds-green-300: hsla(var(--ds-green-300-value),1);
	--ds-green-400: hsla(var(--ds-green-400-value),1);
	--ds-green-500: hsla(var(--ds-green-500-value),1);
	--ds-green-600: hsla(var(--ds-green-600-value),1);
	--ds-green-700: hsla(var(--ds-green-700-value),1);
	--ds-green-800: hsla(var(--ds-green-800-value),1);
	--ds-green-900: hsla(var(--ds-green-900-value),1);
	--ds-green-1000: hsla(var(--ds-green-1000-value),1);
	--ds-teal-100: hsla(var(--ds-teal-100-value),1);
	--ds-teal-200: hsla(var(--ds-teal-200-value),1);
	--ds-teal-300: hsla(var(--ds-teal-300-value),1);
	--ds-teal-400: hsla(var(--ds-teal-400-value),1);
	--ds-teal-500: hsla(var(--ds-teal-500-value),1);
	--ds-teal-600: hsla(var(--ds-teal-600-value),1);
	--ds-teal-700: hsla(var(--ds-teal-700-value),1);
	--ds-teal-800: hsla(var(--ds-teal-800-value),1);
	--ds-teal-900: hsla(var(--ds-teal-900-value),1);
	--ds-teal-1000: hsla(var(--ds-teal-1000-value),1);
	--ds-purple-100: hsla(var(--ds-purple-100-value),1);
	--ds-purple-200: hsla(var(--ds-purple-200-value),1);
	--ds-purple-300: hsla(var(--ds-purple-300-value),1);
	--ds-purple-400: hsla(var(--ds-purple-400-value),1);
	--ds-purple-500: hsla(var(--ds-purple-500-value),1);
	--ds-purple-600: hsla(var(--ds-purple-600-value),1);
	--ds-purple-700: hsla(var(--ds-purple-700-value),1);
	--ds-purple-800: hsla(var(--ds-purple-800-value),1);
	--ds-purple-900: hsla(var(--ds-purple-900-value),1);
	--ds-purple-1000: hsla(var(--ds-purple-1000-value),1);
	--ds-pink-100: hsla(var(--ds-pink-100-value),1);
	--ds-pink-200: hsla(var(--ds-pink-200-value),1);
	--ds-pink-300: hsla(var(--ds-pink-300-value),1);
	--ds-pink-400: hsla(var(--ds-pink-400-value),1);
	--ds-pink-500: hsla(var(--ds-pink-500-value),1);
	--ds-pink-600: hsla(var(--ds-pink-600-value),1);
	--ds-pink-700: hsla(var(--ds-pink-700-value),1);
	--ds-pink-800: hsla(var(--ds-pink-800-value),1);
	--ds-pink-900: hsla(var(--ds-pink-900-value),1);
	--ds-pink-1000: hsla(var(--ds-pink-1000-value),1);
}
```

2024-02-03 20:45 UTC, uncenter commented
Also, the app and pages router icons are unthemed.
![image](https://github.com/catppuccin/userstyles/assets/47499684/3798305c-a7b1-4bd1-b96b-e384daea3a02)

2024-02-04 15:15 UTC, uncenter commented
It actually looks quite good, nice job. Placeholder text in search/input boxes is still unthemed (`input::placeholder`, see https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder).

2024-02-06 03:21 UTC, uncenter commented on styles/nextjs/catppuccin.user.css
> +    }
Also themes the fake placeholder text in the search bar at the top of the page.
```suggestion
    input::placeholder,
    button[class*="navbar_search"] {
      color: @text;
    }
```

2024-02-06 03:37 UTC, uncenter requested changes
Looking good! A few small things I noticed...

**Social icons in footer:**
![Screenshot 2024-02-05 at 22 21 57 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/93f1ba2b-4b61-4b31-ab3c-1609f06cc639)
These SVG icons can be themed, if you click on the element in the dev tools panel:
```html
<img alt="GitHub Logo" loading="lazy" width="16" height="16" decoding="async" data-nimg="1" style="color:transparent" src="/icons/github.svg">
```
You can see that it is an `<img>` tag that links to an SVG. It's a little difficult to explain the process for theming these in a review comment, so I'll just give you the "answer" now and I promise we will document it properly in the future (see #449).

**Light mode:**
Without changing your Next.js theme, change your selected Stylus theme to Latte and observe the website. Looks like you missed a few spots:

Inline code, code block borders.
![Screenshot 2024-02-05 at 22 41 24 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/19dd50a9-4a92-4315-bf6b-353e15834daa)

Theme toggle shouldn't have a border around it.
![Screenshot 2024-02-05 at 22 42 59 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/0a285440-fe6e-468e-93ba-e4036d9de4aa)

These cards look a little strange (compare Next.js dark mode + Latte to Next.js light mode).
![Screenshot 2024-02-05 at 22 43 55 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/68106f38-eb2c-4ff4-941e-7033102375f9)

...and probably a few smaller things, I recommend that you try doing what I did, Latte with Next.js dark mode, to see what spots look off.

2024-02-06 03:38 UTC, uncenter commented on styles/nextjs/catppuccin.user.css
> +    }
Themes the two footer icons.

```suggestion
    .gradient-text {
      --text-gradient: @text;
    }
    
    img[alt="GitHub Logo"] {
      @svg: escape('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="15.673" viewBox="0 0 16 15.673"><path fill="@{subtext0}" fill-rule="evenodd" d="M7.976 0C3.566 0 0 3.592 0 8.035c0 3.552 2.285 6.559 5.454 7.623 0.396 0.08 0.541 -0.173 0.541 -0.386 0 -0.186 -0.013 -0.825 -0.013 -1.49 -2.219 0.479 -2.681 -0.958 -2.681 -0.958 -0.357 -0.931 -0.885 -1.171 -0.885 -1.171 -0.726 -0.492 0.053 -0.492 0.053 -0.492 0.806 0.053 1.228 0.825 1.228 0.825 0.713 1.224 1.862 0.878 2.324 0.665 0.066 -0.519 0.277 -0.878 0.502 -1.078 -1.77 -0.186 -3.632 -0.878 -3.632 -3.965 0 -0.878 0.317 -1.596 0.819 -2.155 -0.079 -0.2 -0.357 -1.024 0.079 -2.129 0 0 0.673 -0.213 2.192 0.825a7.669 7.669 0 0 1 1.994 -0.266c0.673 0 1.36 0.093 1.994 0.266 1.519 -1.038 2.192 -0.825 2.192 -0.825 0.436 1.104 0.158 1.929 0.079 2.129 0.515 0.559 0.819 1.277 0.819 2.155 0 3.087 -1.862 3.765 -3.645 3.965 0.291 0.253 0.541 0.732 0.541 1.49 0 1.078 -0.013 1.942 -0.013 2.208 0 0.213 0.145 0.466 0.541 0.386 3.169 -1.064 5.454 -4.071 5.454 -7.623C15.952 3.592 12.374 0 7.976 0z" clip-rule="evenodd"/></svg>');
      height: 0 !important;
      width: 0 !important;
      padding-left: 16px !important;
      padding-top: 16px !important;
      background: url("data:image/svg+xml,@{svg}") no-repeat !important;
    }
    img[alt="X Logo"] {
      @svg: escape('<svg xmlns="http://www.w3.org/2000/svg" fill="none" height="16" shape-rendering="geometricPrecision" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" viewBox="0 0 24 24" width="16"><path fill="@{subtext0}" d="M16.99 0h3.308l-7.227 8.26 8.502 11.24h-6.657l-5.214-6.817L3.736 19.5H.426l7.73-8.835L0 0h6.826l4.713 6.231L16.99 0Zm-1.161 17.52h1.833L5.83 1.876H3.863L15.829 17.52Z" stroke="none"/></svg>');
      height: 0 !important;
      width: 0 !important;
      padding-left: 16px !important;
      padding-top: 16px !important;
      background: url("data:image/svg+xml,@{svg}") no-repeat !important;
    }
```

2024-02-06 13:49 UTC, Dandraghas commented
> Without changing your Next.js theme, change your selected Stylus theme to Latte and observe the website. Looks like you missed a few spots:
>
> Inline code, code block borders.

I am not sure why it looks like that for you

my screenshot
![image](https://github.com/catppuccin/userstyles/assets/91272905/4731de3e-83b2-407a-af56-78fdb71fa5de)
your screenshot:
![image](https://github.com/catppuccin/userstyles/assets/91272905/a66836e0-af2f-4533-a13e-06ba1d31a967)

same for cards on latte:
![image](https://github.com/catppuccin/userstyles/assets/91272905/4e660cb9-4ba6-4aa3-9edc-e3eb9abaafae)

your screenshot:
![image](https://github.com/catppuccin/userstyles/assets/91272905/7c52122c-ce24-4b25-a180-589a05cf7ec7)

I don't have any borders on inline code blocks, nor shadows on cards like you have

i mainly use firefox so i tried chromium, but i still unable to reproduce what you have

2024-02-07 17:50 UTC, uncenter requested changes

2024-02-07 17:50 UTC, uncenter commented on styles/nextjs/catppuccin.user.css
> +    }
```suggestion
    .features_card__xYla9,
    .foundation_root__wm0ez,
    .foundation_card__v7VKB {
      background: @base;
    }
```

2024-02-07 17:50 UTC, uncenter commented on styles/nextjs/catppuccin.user.css
> +    }
```suggestion
    .gradient,
    .gradient-text {
      --text-gradient: @text;
    }
```

2024-02-07 17:55 UTC, uncenter commented
The https://nextjs.org/learn page has a few unthemed elements, most of it is fine though. Just scroll through different parts and toggle the userstyle on and off and see what needs to be changed.

Also, `--ds-gray-700` needs to be themed for the docs breadcrumbs:

![Screenshot 2024-02-07 at 12 54 22 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/33c4cd1f-6b44-4edd-b8c9-a3a8938d97b2)

2024-02-07 21:37 UTC, uncenter requested changes
Almost done! The hover color of the icons on these cards on the Learn page are unthemed. 
![Screenshot 2024-02-07 at 16 36 09 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/9882e53e-d2b1-47f2-aee6-a45583c69cde)

2024-02-07 21:37 UTC, uncenter commented on styles/nextjs/catppuccin.user.css
> +    }
```suggestion
    td a {
      color: @accent-color;
    }
```

2024-02-08 20:42 UTC, uncenter requested changes

2024-02-08 20:50 UTC, uncenter requested changes

2024-02-08 20:50 UTC, uncenter commented on styles/nextjs/catppuccin.user.css
> +    }
The following suggestion themes the mobile/small screen nav menu:
![Screenshot 2024-02-08 at 15 44 08 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/8785e4c3-dc05-4511-864f-0a5478b17553)

```suggestion
    .header_header__zJOD0 {
      background: @base;
    }
    .mute, .subtitle {
      color: @subtext0;
    }

    .mobile-menu_mobileMenu__xqbOP a.mobile-menu_selected__G55UL {
      color: var(--geist-background);
    }

    .dark-theme .dark\:bg-black\/50 {
      background-color: var(--geist-background);
    }
```

2024-02-08 22:00 UTC, uncenter approved these changes

2024-02-08 22:02 UTC, uncenter commented
Syntax highlighting isn't done yet but I'll figure that out for you, I'm pretty familiar with what they are using for syntax highlighting and it won't take long but I haven't had time to do it yet. I think it is fine to merge for now and I'll do a PR later.

2024-02-09 02:30 UTC, uncenter commented on styles/nextjs/catppuccin.user.css
> +
Code block syntax highlighting!
```suggestion

      .code-block_pre___OLfy {
        --shiki-token-punctuation: @overlay2;
        --shiki-token-constant: @peach;
        --shiki-token-string: @green;
        --shiki-token-string-expression: @green;
        --shiki-token-comment: @overlay0;
        --shiki-token-keyword: @mauve;
        --shiki-token-parameter: @maroon;
        --shiki-token-function: @blue;
      }

```

2024-02-09 02:30 UTC, uncenter commented on styles/nextjs/catppuccin.user.css
> +    --ds-gray-700: @subtext0;
Line numbers in code blocks.
```suggestion
    --ds-gray-400: @surface0;
    --ds-gray-600: @overlay1;
    --ds-gray-700: @subtext0;
```

2024-02-09 14:58 UTC, uncenter approved these changes

2024-02-09 18:28 UTC, isabelroses approved these changes
Thanks for the PR and working along @uncenter suggestions.

2024-02-09 18:28 UTC, merged

2024-02-09 19:33 UTC, uncenter commented
> Thanks for the PR and working along @uncenter suggestions.

Yeah sorry for all my nitpicks :sob: