feat(holodex): init
catppuccin/userstyles pull request #555
Opened 2024-02-24 22:09 UTC by Guaxinim5573

## 🎉 Theme for [Holodex](https://holodex.net) 🎉
[Holodex.net](https://holodex.net) is the website built by fans for fans to watch all their favorite virtual youtubers.

![mocha](https://github.com/catppuccin/userstyles/assets/49736632/a9d9cbcb-a793-4d37-9838-926790ba123d)

## 💬 Additional Comments 💬
Holodex's selected theme is ignored.

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [submission guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md).
- [x] I have made a new directory underneath `/styles/<name-of-website>` containing the contents of the [`/template`](https://github.com/catppuccin/userstyles/blob/main/template/) directory.
  - [x] I have ensured that the new directory is in **lower-kebab-case**.
  - [x] I have followed the template and kept the preprocessor as [LESS](https://lesscss.org/#overview).
- [x] I have made sure to update the
      [`userstyles.yml`](https://github.com/catppuccin/userstyles/blob/main/scripts/userstyles.yml)
      file with information about the new userstyle.
- [x] I have included the following files:
  - `catppuccin.user.css` - all the CSS for the userstyle, based on the
    template.
  - `assets/mocha.webp`, `assets/macchiato.webp`, `assets/frappe.webp` and
    `assets/latte.webp` - individual screenshots of the themed website, in all 4
    Catppuccin flavors.
  - `catwalk.webp` - image of all individual screenshots stitched together,
    generated via [Catwalk](https://github.com/catppuccin/toolbox/tree/main/catwalk#readme).

2024-02-25 10:02 UTC, isabelroses requested changes
First of all thanks for the PR, but there will need to be some changes.

- Text is not themed on most pages.
- It would be nice if streamers names where colored with the accent.
- We should also theme the red colors, in the image below.
![image](https://github.com/catppuccin/userstyles/assets/71222764/07787571-a9cd-43d6-a7d0-5c119af8d978)

2024-02-25 10:02 UTC, isabelroses commented on styles/holodex/catppuccin.user.css
> +    }
Can you remove this line? Or does it fix some issue.

2024-02-29 04:12 UTC, Guaxinim5573 commented
I've updated the theme with changes you requested.
![image](https://github.com/catppuccin/userstyles/assets/49736632/874b1848-ada8-4c62-90cd-0a7d929da9ab)

Now Holodex's selected theme is ignored in favor of Catppuccin's accent color on Stylus.
<details><summary>Latte</summary><img src="https://github.com/catppuccin/userstyles/assets/49736632/782a8167-34b6-4d76-85cc-91247cffa822"></details>
<details><summary>Mocha</summary><img src="https://github.com/catppuccin/userstyles/assets/49736632/aa5ec7bc-ccd7-4eca-ae0b-f9895f9eb69d"></details>

2024-02-29 08:33 UTC, isabelroses requested changes
Just 1 last change and this PR should be good to go.

2024-02-29 08:33 UTC, isabelroses commented on styles/holodex/catppuccin.user.css
> +    & {
we don't need to have the `&{}` here

2024-02-29 10:57 UTC, merged

2024-02-29 10:58 UTC, isabelroses commented
Thanks for the pr <3