fix(proton): light color scheme for message iframe
catppuccin/userstyles pull request #919
Opened 2024-05-25 22:48 UTC by Lichthagel

## 🔧 What does this fix? 🔧

Fixes #828 by setting `color-scheme: light;` for the iframe containing the message.

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [x] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

2024-05-25 22:49 UTC, uncenter approved these changes

2024-05-25 22:50 UTC, Lichthagel commented
Similar approach might fix #902. Will take a look tomorrow.

2024-05-26 02:46 UTC, soya-daizu reviewed
The problem is that when the email is just a plantext, it already shows light text with dark background and works fine. I personally don't want to force everything to be in light color scheme if it blends in to the dark color scheme.
I will look into the problem and try if I could fix this without forcing light color.

2024-05-26 03:05 UTC, soya-daizu requested changes

2024-05-26 03:05 UTC, soya-daizu commented on styles/proton/catppuccin.user.css
> +    .message-iframe iframe {
Okay, I think this works:

```suggestion
    .message-content:not(.plain) .message-iframe iframe
```

2024-05-26 10:25 UTC, soya-daizu approved these changes

2024-06-01 21:32 UTC, merged