fix(google-photos): assorted changes
catppuccin/userstyles pull request #924
Opened 2024-05-28 04:38 UTC by GenShibe

## 🔧 What does this fix? 🔧
closes #906 (i'm 99% sure anyways...)

## 🗒 Checklist 🗒

- [x] I have read and followed Catppuccin's [contributing guidelines](https://github.com/catppuccin/userstyles/blob/main/docs/CONTRIBUTING.md).
- [x] I have updated the version appropriately in the `==UserStyle==` header of the `catppuccin.user.css` file.

2024-05-28 23:18 UTC, isabelroses submitted a review, later dismissed

2024-05-29 01:52 UTC, uncenter requested changes
There are a lot of classes here and almost all of them without comments. This is really quite unmaintainable. At this rate this userstyle will need a rewrite at some point soon purely do to us having to add on new classes and not knowing if it is safe to remove others...

2024-05-29 16:02 UTC, GenShibe commented
> There are a lot of classes here and almost all of them without comments. This is really quite unmaintainable. At this rate this userstyle will need a rewrite at some point soon purely do to us having to add on new classes and not knowing if it is safe to remove others...

hopefully i fixed this with the new commit, feel free to nitpick as needed

2024-06-08 15:01 UTC, isabelroses approved these changes

2024-06-08 15:07 UTC, uncenter requested changes

2024-06-08 15:07 UTC, uncenter commented on styles/google-photos/catppuccin.user.css
>      }
Blue or accent? Typically blue is used as Google's accent color.

2024-06-08 15:07 UTC, uncenter commented on styles/google-photos/catppuccin.user.css
> +    }
Same as above, probably should be accent.

2024-06-08 15:07 UTC, uncenter commented on styles/google-photos/catppuccin.user.css
> +    }
Just use `subtext0` here I think.

2024-06-08 23:57 UTC, uncenter requested changes
Again on the blue vs accent color thing - I'd just search for `@blue` in this entire userstyle and make sure any instances of it are really only for links or in SVGs. Most cases I can see scrolling through should be accent instead of blue.

2024-06-09 17:59 UTC, uncenter approved these changes

2024-06-10 02:13 UTC, merged